const NAV=[["summary","⌂","Resumen"],["activities","▤","Actividades"],["stages","◇","Etapas"],["incidents","△","Incidencias"],["evidence","▣","Evidencias"],["team","♙","Equipo"],["reports","▥","Reportes"]];
export default function TraceProjectShell({view,onView,projects=[],projectId,onProjectChange,incidentCount=0,userLabel="Usuario",children}){
 const active=projects.find(p=>p.id===projectId)||projects[0]||null;
 return <div className="min-h-screen bg-[#f6f8fb] text-slate-950">
  <aside className="fixed inset-y-0 left-0 z-40 flex w-[264px] flex-col bg-[#07111f] text-white">
   <div className="px-5 pb-5 pt-7"><div className="text-2xl font-black tracking-tight">KAWVO <span className="font-semibold text-blue-500">Trace</span></div></div>
   <div className="px-4"><div className="rounded-xl border border-slate-600/80 p-3"><select value={projectId||active?.id||""} onChange={e=>onProjectChange?.(e.target.value)} className="w-full bg-transparent text-sm font-black outline-none">{projects.map(p=><option key={p.id} value={p.id} className="text-slate-950">{p.name}</option>)}</select><div className="mt-2 flex items-center gap-2 text-xs text-slate-300"><span className={`h-2.5 w-2.5 rounded-full ${active?.status==='active'?'bg-emerald-500':'bg-slate-400'}`}/>{active?.status==='active'?'Activo':active?.status||'Proyecto'}</div></div></div>
   <nav className="mt-5 flex-1 space-y-1 overflow-y-auto px-3">{NAV.map(([k,i,l])=><button key={k} onClick={()=>onView?.(k)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold ${view===k?'bg-blue-600 text-white':'text-slate-200 hover:bg-white/10'}`}><span className="grid w-6 place-items-center text-lg">{i}</span><span className="flex-1">{l}</span>{k==='incidents'&&incidentCount>0&&<span className="grid h-6 min-w-6 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-black">{incidentCount}</span>}</button>)}</nav>
   <div className="border-t border-white/10 px-3 py-4"><a href="/dashboard/links" className="flex items-center gap-3 rounded-xl border border-blue-500 px-3 py-3 text-sm font-black"><span className="grid w-6 place-items-center">▦</span><span className="flex-1">Panel QR Code</span><span className="text-xl">→</span></a><button onClick={()=>onView?.('settings')} className={`mt-3 flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold ${view==='settings'?'bg-white/10 text-white':'text-slate-200'}`}><span>⚙</span><span>Configuración</span></button><button onClick={()=>onView?.('help')} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold text-slate-200"><span>?</span><span>Ayuda</span></button></div>
   <div className="border-t border-white/10 p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-600 text-xs font-black">{String(userLabel).slice(0,2).toUpperCase()}</span><span className="truncate text-sm font-semibold">{userLabel}</span></div></div>
  </aside>
  <main className="min-h-screen pl-[264px]"><div className="p-6 xl:p-8">{children}</div></main>
 </div>
}
