import{useEffect,useMemo,useState}from'react';
const BASE=import.meta.env.VITE_API_URL||'https://api.code.intaprd.com';
function token(){return localStorage.getItem('qr_token')||''}
async function api(path,options={}){const r=await fetch(`${BASE}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d}
const TYPES={executive:'Ejecutivo',traceability:'Trazabilidad',incidents:'Incidencias',evidence:'Evidencias',compliance:'Cumplimiento',analytics:'Analítica',client:'Cliente'};
const STATUS={ready:'Listo',generating:'Generando',failed:'Error',shared:'Compartido',archived:'Archivado'};
const fmt=v=>v?new Date(v).toLocaleString('es-DO',{dateStyle:'medium',timeStyle:'short'}):'—';
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`};
const today=()=>new Date().toISOString().slice(0,10);
export default function TraceReportsCanvas({projectId}){
 const[data,setData]=useState(null),[selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(false);
 const[query,setQuery]=useState(''),[typeFilter,setTypeFilter]=useState(''),[statusFilter,setStatusFilter]=useState('');
 const[form,setForm]=useState({type:'executive',title:'',from:monthStart(),to:today(),sections:['summary','stages','activities','incidents','approvals','evidence']});
 async function load(){if(!projectId)return;setLoading(true);setError('');try{const q=new URLSearchParams();if(query)q.set('q',query);if(typeFilter)q.set('type',typeFilter);if(statusFilter)q.set('status',statusFilter);const d=await api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/reports?${q}`);setData(d.data||null);const first=d.data?.items?.[0];setSelectedId(id=>d.data?.items?.some(x=>x.id===id)?id:(first?.id||''))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function loadDetail(id){if(!id||!projectId){setDetail(null);return}try{const d=await api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/reports/${encodeURIComponent(id)}`);setDetail(d.data||null)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[projectId,typeFilter,statusFilter]);
 useEffect(()=>{if(selectedId)loadDetail(selectedId);else setDetail(null)},[selectedId]);
 async function create(){setBusy(true);setError('');try{const d=await api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/reports`,{method:'POST',body:JSON.stringify({type:form.type,title:form.title||undefined,scope:{type:'project'},period:{from:form.from||null,to:form.to||null},sections:form.sections})});setModal(false);await load();setSelectedId(d.data.id);setDetail(d.data)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const items=data?.items||[],summary=data?.summary||{};
 const included=useMemo(()=>detail?.definition?.sections||[],[detail]);
 return <div className="mx-auto max-w-[1500px] space-y-5">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
   <div><h1 className="text-3xl font-black text-slate-950">Reportes</h1><p className="mt-1 text-sm text-slate-500">Genera, consulta y conserva fotografías verificables del estado del proyecto.</p></div>
   <button onClick={()=>setModal(true)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-sm">＋ Generar reporte</button>
  </header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
   ['Reportes generados',summary.generated||0,'Total acumulado'],['Este mes',summary.thisMonth||0,'Generados este mes'],['Programados',summary.scheduled||0,'Entregas futuras'],['Compartidos',summary.shared||0,'Con acceso compartido']
  ].map(([k,v,s])=><div key={k} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{k}</div><div className="mt-2 text-2xl font-black text-slate-950">{v}</div><div className="mt-1 text-[11px] text-slate-400">{s}</div></div>)}</div>
  <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]">
   <section className="min-w-0 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_180px_160px_auto]">
     <input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Buscar reportes…" className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-blue-400"/>
     <select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Todos los tipos</option>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
     <select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-3 text-sm"><option value="">Todos los estados</option>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>
     <button onClick={load} className="rounded-xl border border-slate-200 px-4 py-3 text-xs font-black text-slate-600">Buscar</button>
    </div>
    <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200">
     {loading?<div className="p-8 text-center text-sm text-slate-400">Cargando reportes…</div>:items.length===0?<div className="p-10 text-center"><div className="text-sm font-black text-slate-700">Todavía no hay reportes generados</div><p className="mt-1 text-xs text-slate-400">El primer reporte conservará un snapshot inmutable de los datos actuales.</p></div>:items.map(r=><button key={r.id} onClick={()=>setSelectedId(r.id)} className={`grid w-full grid-cols-[minmax(0,1fr)_120px_145px_90px] items-center gap-3 border-b border-slate-100 px-4 py-4 text-left last:border-0 ${selectedId===r.id?'bg-blue-50/70':'hover:bg-slate-50'}`}>
      <div className="min-w-0"><div className="truncate text-sm font-black text-slate-900">{r.title}</div><div className="mt-1 truncate text-[11px] text-slate-400">{r.description||r.code}</div></div>
      <span className="truncate text-xs font-semibold text-slate-600">{TYPES[r.type]||r.type}</span>
      <span className="text-[11px] text-slate-500">{fmt(r.generatedAt)}</span>
      <span className={`justify-self-start rounded-lg px-2.5 py-1 text-[9px] font-black ${r.status==='ready'?'bg-emerald-50 text-emerald-700':r.status==='shared'?'bg-violet-50 text-violet-700':'bg-slate-100 text-slate-600'}`}>{STATUS[r.status]||r.status}</span>
     </button>)}
    </div>
    <div className="mt-4 text-[11px] text-slate-400">Mostrando {items.length} reporte{items.length===1?'':'s'}</div>
   </section>
   <aside className="min-h-[520px] rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    {!detail?<div className="grid h-full min-h-[420px] place-items-center text-center"><div><div className="text-sm font-black text-slate-700">Selecciona un reporte</div><p className="mt-1 text-xs text-slate-400">Aquí verás su snapshot, cobertura y opciones de salida.</p></div></div>:<>
     <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-black uppercase tracking-[.12em] text-blue-600">{detail.code}</div><h2 className="mt-2 overflow-hidden text-xl font-black leading-tight text-slate-950 [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]">{detail.title}</h2></div><span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-700">{STATUS[detail.status]||detail.status}</span></div>
     <div className="mt-5 rounded-2xl border border-slate-200 bg-gradient-to-br from-slate-50 to-blue-50 p-5"><div className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">KAWVO TRACE</div><div className="mt-8 text-2xl font-black text-slate-950">{TYPES[detail.type]||'Reporte'}</div><div className="mt-2 text-sm font-semibold text-slate-600">{detail.snapshot?.project?.name||data?.project?.name||'Proyecto'}</div><div className="mt-10 text-[10px] text-slate-400">Snapshot · {fmt(detail.snapshot?.snapshotAt||detail.generatedAt)}</div></div>
     <div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-4 border-y border-slate-100 py-5"><Meta label="Tipo" value={TYPES[detail.type]||detail.type}/><Meta label="Cobertura" value={detail.scope?.type==='project'?'Todo el proyecto':detail.scope?.type}/><Meta label="Generado" value={fmt(detail.generatedAt)}/><Meta label="Generado por" value={detail.generatedByEmail||'—'}/><Meta label="Avance congelado" value={`${detail.snapshot?.summary?.progress??0}%`}/><Meta label="Incidencias abiertas" value={detail.snapshot?.summary?.openIncidents??0}/></div>
     <div className="mt-5"><div className="text-xs font-black text-slate-900">Incluye</div><div className="mt-3 space-y-2">{included.map(x=><div key={x} className="flex items-center gap-2 text-xs text-slate-600"><span className="grid h-4 w-4 place-items-center rounded-full bg-blue-50 text-[9px] font-black text-blue-600">✓</span>{sectionLabel(x)}</div>)}</div></div>
     <div className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="text-xs font-black text-blue-700">Fuente verificable</div><p className="mt-1 text-[11px] leading-5 text-blue-700/75">Este reporte fue congelado a partir de registros reales de KAWVO Trace. Sus cifras no cambian cuando el proyecto continúa avanzando.</p></div>
     <div className="mt-5 grid grid-cols-2 gap-2"><button onClick={()=>window.print()} className="rounded-xl border border-blue-200 px-4 py-3 text-xs font-black text-blue-600">Imprimir</button><button className="rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white">Ver reporte</button></div>
     <div className="mt-2 grid grid-cols-3 gap-2">{['PDF','DOCX','XLSX'].map(x=><button key={x} disabled className="rounded-xl border border-slate-200 px-3 py-2.5 text-[10px] font-black text-slate-400" title="Renderer documental en el siguiente bloque">{x}</button>)}</div>
    </>}
   </aside>
  </div>
  {modal&&<GenerateModal form={form} setForm={setForm} busy={busy} onClose={()=>setModal(false)} onCreate={create}/>} 
 </div>
}
function Meta({label,value}){return <div className="min-w-0"><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</div><div title={String(value??'—')} className="mt-1 truncate text-xs font-semibold text-slate-700">{value??'—'}</div></div>}
function sectionLabel(v){return({summary:'Resumen general del proyecto',stages:'Etapas y avance',activities:'Cumplimiento de actividades',timeline:'Trazabilidad cronológica',incidents:'Incidencias y correcciones',approvals:'Decisiones y aprobaciones',evidence:'Evidencias registradas'})[v]||v}
function GenerateModal({form,setForm,busy,onClose,onCreate}){const toggle=s=>setForm(f=>({...f,sections:f.sections.includes(s)?f.sections.filter(x=>x!==s):[...f.sections,s]}));return <div className="fixed inset-0 z-[170] grid place-items-center bg-slate-950/45 p-4" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black text-slate-950">Generar reporte</h2><p className="mt-1 text-xs text-slate-500">TRACE congelará los datos reales del proyecto en un snapshot histórico.</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200">×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-black text-slate-700">Tipo<select value={form.type} onChange={e=>setForm(f=>({...f,type:e.target.value,title:''}))} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-normal">{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-xs font-black text-slate-700">Título opcional<input value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="TRACE genera uno automáticamente" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-black text-slate-700">Desde<input type="date" value={form.from} onChange={e=>setForm(f=>({...f,from:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-black text-slate-700">Hasta<input type="date" value={form.to} onChange={e=>setForm(f=>({...f,to:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm font-normal"/></label></div><div className="mt-5"><div className="text-xs font-black text-slate-700">Contenido</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{['summary','stages','activities','incidents','approvals','evidence'].map(s=><label key={s} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs font-semibold text-slate-600"><input type="checkbox" checked={form.sections.includes(s)} onChange={()=>toggle(s)}/>{sectionLabel(s)}</label>)}</div></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-slate-200 px-5 py-3 text-xs font-black text-slate-600">Cancelar</button><button disabled={busy||!form.sections.length} onClick={onCreate} className="rounded-xl bg-blue-600 px-5 py-3 text-xs font-black text-white disabled:opacity-50">{busy?'Generando snapshot…':'Generar reporte'}</button></div></div></div>}
