import { useMemo, useState } from "react";
const SECTORS=[['all','Todos los sectores'],['construction','Construcción y obras'],['property','Propiedades y entregas'],['maintenance','Mantenimiento'],['rental','Alquileres'],['logistics','Logística'],['warehouse','Almacenes'],['hospitality','Hotelería y servicios'],['other','Otros']];
const ART=['🏗️','🧰','🏢','🛠️','🏠','🚚','📦','🏨'];
function industryName(v){return({construction:'Construcción',property:'Propiedades',maintenance:'Mantenimiento',rental:'Alquileres',logistics:'Logística',warehouse:'Almacenes',hospitality:'Hotelería',quality:'Calidad',service:'Servicios'}[v]||'Operaciones')}

export default function TraceSolutionsLibrary({templates=[],selected,onSelect,onUse}){
 const [sector,setSector]=useState('all');const [query,setQuery]=useState('');
 const filtered=useMemo(()=>templates.filter(t=>{const sectorOk=sector==='all'||t.industry===sector||(sector==='other'&&!SECTORS.some(([k])=>k===t.industry));const q=query.trim().toLowerCase();const text=`${t.name||''} ${t.description||''} ${industryName(t.industry)}`.toLowerCase();return sectorOk&&(!q||text.includes(q))}),[templates,sector,query]);
 const current=(selected&&filtered.some(t=>t.id===selected.id)?selected:filtered[0])||null;
 function choose(t){onSelect(t)}
 return <div className="mx-auto grid max-w-[1560px] gap-5 xl:grid-cols-[220px_minmax(0,1fr)_340px]">
  <aside className="h-fit rounded-2xl border border-slate-200 bg-white p-4 shadow-sm xl:sticky xl:top-[94px]"><div className="text-xs font-black uppercase tracking-[.16em] text-slate-400">Sectores</div><div className="mt-3 space-y-1">{SECTORS.map(([key,label])=>{const count=key==='all'?templates.length:key==='other'?templates.filter(t=>!SECTORS.some(([k])=>k===t.industry)).length:templates.filter(t=>t.industry===key).length;return <button key={key} onClick={()=>setSector(key)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-xs font-semibold ${sector===key?'bg-blue-50 text-blue-700':'text-slate-600 hover:bg-slate-50'}`}><span>{label}</span><span className="text-[10px] text-slate-400">{count}</span></button>})}</div><div className="mt-5 rounded-2xl bg-slate-950 p-4 text-white"><div className="text-xs font-black">¿No encuentras tu proceso?</div><p className="mt-2 text-[11px] leading-5 text-slate-300">Puedes partir de una solución personalizada sin perder controles, evidencias, incidencias ni trazabilidad.</p><button className="mt-4 w-full rounded-xl bg-white px-3 py-2 text-[11px] font-bold text-slate-900">Crear personalizada</button></div></aside>

  <section className="min-w-0"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Biblioteca de soluciones</div><h1 className="mt-1 text-3xl font-black tracking-tight">Empieza con el control ya preparado</h1><p className="mt-1 text-sm text-slate-500">TRACE carga la estructura; tú solo asignas responsables y ajustas lo particular.</p></div><div className="relative w-full max-w-sm"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-xs outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50" placeholder="Buscar soluciones, procesos, controles…"/></div></div>
   <div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{filtered.length} soluciones encontradas</span>{(sector!=='all'||query)&&<button onClick={()=>{setSector('all');setQuery('')}} className="text-xs font-bold text-blue-600">Limpiar filtros</button>}</div>
   <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{filtered.map((t,i)=>{const active=current?.id===t.id;return <button key={t.id} onClick={()=>choose(t)} className={`group overflow-hidden rounded-2xl border bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-md ${active?'border-blue-500 ring-2 ring-blue-100':'border-slate-200'}`}><div className={`grid aspect-[2.05/1] place-items-center bg-gradient-to-br ${['from-blue-50 to-cyan-100','from-indigo-50 to-slate-100','from-amber-50 to-blue-50','from-orange-50 to-slate-100','from-emerald-50 to-blue-50','from-sky-50 to-slate-100'][i%6]}`}><div className="relative flex h-24 w-40 items-end justify-center gap-2 rounded-2xl border border-white/80 bg-white/80 p-3 shadow-sm"><span className="absolute -right-2 -top-2 grid h-7 w-7 place-items-center rounded-lg bg-blue-600 text-xs text-white">{ART[i%ART.length]}</span><div className="grid w-full grid-cols-3 gap-1"><i className="h-10 rounded bg-blue-100"/><i className="h-14 rounded bg-slate-100"/><i className="h-8 rounded bg-emerald-100"/></div></div></div><div className="p-4"><div className="flex items-center justify-between"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-600">{industryName(t.industry)}</span>{active&&<span className="grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-[10px] font-black text-white">✓</span>}</div><h3 className="mt-3 text-base font-black text-slate-900">{t.name}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{t.description}</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full border border-slate-200 px-2 py-1 text-[9px] font-bold text-slate-500">{t.stages?.length||0} pasos listos</span><span className="rounded-full border border-blue-200 bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">Vista pública</span></div></div></button>})}</div>
   {!filtered.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="text-3xl">⌕</div><h3 className="mt-3 font-black">No encontramos una solución con esos filtros</h3><p className="mt-1 text-xs text-slate-500">Prueba otro sector o limpia la búsqueda.</p></div>}
  </section>

  <aside className="h-fit xl:sticky xl:top-[94px]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">Vista previa de la solución</div>{current?<><div className="mt-4 flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-2xl">{ART[Math.max(0,templates.findIndex(t=>t.id===current.id))%ART.length]}</span><div><h2 className="font-black text-slate-900">{current.name}</h2><p className="mt-1 text-[11px] leading-5 text-slate-500">{current.description}</p></div></div><div className="mt-5 border-t border-slate-100 pt-4"><div className="text-xs font-black">Etapas incluidas</div><div className="mt-3 space-y-2">{(current.stages||[]).slice(0,8).map((s,i)=><div key={s.key||i} className="flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded-md bg-blue-50 text-[9px] font-black text-blue-700">{i+1}</span><span className="text-[11px] font-semibold text-slate-600">{s.name}</span></div>)}</div></div><div className="mt-5 border-t border-slate-100 pt-4"><div className="text-xs font-black">Participantes sugeridos</div><div className="mt-3 grid grid-cols-2 gap-2">{['Responsable','Supervisión','Calidad','Cliente / usuario'].map((x,i)=><div key={x} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2"><span className={`grid h-7 w-7 place-items-center rounded-full text-[9px] font-black ${i===3?'bg-emerald-100 text-emerald-700':'bg-blue-100 text-blue-700'}`}>{['R','S','C','U'][i]}</span><span className="text-[10px] font-semibold text-slate-600">{x}</span></div>)}</div></div><div className="mt-5 border-t border-slate-100 pt-4"><div className="text-xs font-black">Incluye</div><div className="mt-3 space-y-2 text-[11px] text-slate-600">{['Evidencias con foto y ubicación','Incidencias y correcciones','Listas de verificación','Vista pública para clientes'].map(x=><div key={x} className="flex gap-2"><span className="text-emerald-600">✓</span><span>{x}</span></div>)}</div></div><button onClick={()=>onUse(current)} className="mt-6 w-full rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white shadow-lg shadow-blue-100 hover:bg-blue-700">Usar esta solución</button></>:<div className="py-12 text-center text-sm text-slate-400">Selecciona una solución.</div>}</div></aside>
 </div>
}
