import { useMemo, useState } from "react";
function initials(email='?'){return email.split('@')[0].split(/[._-]/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'?'}

export default function TraceTeamDirectory({users=[],departments=[]}){
 const [mode,setMode]=useState('people');const [query,setQuery]=useState('');
 const filtered=useMemo(()=>users.filter(u=>`${u.email||''} ${u.role||''}`.toLowerCase().includes(query.trim().toLowerCase())),[users,query]);
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="inline-flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><button onClick={()=>setMode('people')} className={`rounded-lg px-3 py-2 text-xs font-black ${mode==='people'?'bg-blue-600 text-white':'text-slate-500'}`}>Personas</button><button onClick={()=>setMode('structure')} className={`rounded-lg px-3 py-2 text-xs font-black ${mode==='structure'?'bg-blue-600 text-white':'text-slate-500'}`}>Estructura</button></div><div className="flex gap-2"><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} className="rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-xs" placeholder="Buscar persona o rol…"/></div><button className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">+ Invitar persona</button></div></div>

  {mode==='people'?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">{filtered.map((u,i)=><div key={u.id} draggable onDragStart={e=>e.dataTransfer.setData('trace-user-id',u.id)} className="group rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md"><div className={`grid aspect-[1.35/1] place-items-center rounded-xl ${['bg-slate-950','bg-blue-700','bg-indigo-700','bg-emerald-700','bg-amber-600'][i%5]} text-4xl font-black text-white`}>{initials(u.email)}</div><div className="mt-3 flex items-start justify-between gap-2"><div className="min-w-0"><div className="truncate text-xs font-black text-slate-900">{u.email?.split('@')[0]}</div><div className="truncate text-[10px] text-slate-400">{u.email}</div></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">{u.role||'Miembro'}</span></div><div className="mt-3 rounded-xl border border-dashed border-slate-200 bg-slate-50 px-3 py-2 text-[10px] text-slate-500">Arrastra esta persona sobre una etapa o actividad para asignarla.</div></div>)}{!filtered.length&&<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-400">No se encontraron personas.</div>}</div>:
  <div className="relative min-h-[560px] overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="absolute inset-0 opacity-60" style={{backgroundImage:'radial-gradient(#cbd5e1 1px, transparent 1px)',backgroundSize:'20px 20px'}}/><div className="relative z-10 p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Mapa de responsabilidades</h2><p className="text-xs text-slate-500">Vista gráfica de personas, equipos y áreas disponibles.</p></div><button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">Organizar automáticamente</button></div><div className="mt-10 flex justify-center"><div className="rounded-2xl border-2 border-blue-500 bg-blue-50 px-8 py-5 text-center shadow-sm"><div className="text-xs font-black text-blue-800">Administración TRACE</div><div className="mt-1 text-[10px] text-blue-600">Espacio operativo</div></div></div><div className="mx-auto h-12 w-px bg-slate-300"/><div className="mx-auto h-px max-w-4xl bg-slate-300"/><div className="mx-auto grid max-w-5xl gap-4 pt-6 md:grid-cols-3">{(departments.length?departments:[{id:'ops',name:'Operaciones'},{id:'quality',name:'Calidad'},{id:'support',name:'Supervisión'}]).slice(0,6).map((d,idx)=><div key={d.id||idx} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="text-xs font-black">{d.name}</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-500">Equipo</span></div><div className="mt-4 flex -space-x-2">{filtered.slice(idx,idx+3).map(u=><span key={u.id} title={u.email} className="grid h-9 w-9 place-items-center rounded-full border-2 border-white bg-slate-900 text-[9px] font-black text-white">{initials(u.email)}</span>)}</div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-[10px] text-slate-500">Responsabilidades y controles asignados aparecerán aquí.</div></div>)}</div></div></div>}
 </div>
}
