import { useMemo, useState } from "react";

const STEPS=['Qué quieres controlar','Datos de la operación','Quiénes participarán','Cómo se registrará'];
const SECTOR_LABEL={construction:'Construcción y obras',property:'Propiedades y entregas',maintenance:'Mantenimiento',rental:'Alquileres',logistics:'Logística',warehouse:'Almacenes',hospitality:'Hotelería y servicios'};
function initials(email='?'){return email.split('@')[0].split(/[._-]/).slice(0,2).map(p=>p[0]?.toUpperCase()).join('')||'?'}

export default function TraceGuidedControlWizard({open,solution,templates=[],options={users:[],departments:[]},name,setName,selectedUsers=[],selectedDepartments=[],toggleUser,toggleDepartment,publicView,setPublicView,busy,onClose,onCreate,onSelectSolution}){
 const [step,setStep]=useState(0),[audience,setAudience]=useState('client'),[sector,setSector]=useState('all');
 const sectors=useMemo(()=>['all',...new Set(templates.map(t=>t.industry).filter(Boolean))],[templates]);
 const suggestions=useMemo(()=>templates.filter(t=>sector==='all'||t.industry===sector).slice(0,9),[templates,sector]);
 if(!open)return null;
 const canNext=step!==1||name.trim();
 const users=options.users||[];
 const selected=users.filter(u=>selectedUsers.includes(u.id));
 const available=users.filter(u=>!selectedUsers.includes(u.id));
 const addByDrop=ev=>{ev.preventDefault();const id=ev.dataTransfer.getData('text/trace-participant');if(id&&!selectedUsers.includes(id))toggleUser(id)};
 return <div className="fixed inset-0 z-[100] bg-slate-950/55 backdrop-blur-sm"><div className="absolute inset-3 overflow-hidden rounded-[26px] bg-white shadow-2xl md:inset-6"><div className="flex h-full flex-col">
  <header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Nuevo control guiado</div><p className="mt-1 text-xs text-slate-500">Partimos de una solución lista. Tú defines contexto, personas y lo que compartirás.</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 text-slate-500">×</button></header>
  <div className="border-b border-slate-100 px-5 py-3"><div className="grid grid-cols-4 gap-2">{STEPS.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className="flex items-center gap-2 text-left"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-[10px] font-black ${i===step?'bg-blue-600 text-white':i<step?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-400'}`}>{i<step?'✓':i+1}</span><span className={`hidden text-[10px] font-bold md:block ${i===step?'text-slate-900':'text-slate-400'}`}>{s}</span></button>)}</div></div>
  <div className="grid min-h-0 flex-1 lg:grid-cols-[minmax(0,1fr)_350px]"><main className="min-h-0 overflow-y-auto p-5 lg:p-7">
   {step===0&&<div><h1 className="text-3xl font-black tracking-tight">¿Qué quieres controlar?</h1><p className="mt-2 text-sm text-slate-500">Elige una solución preparada. No empiezas desde una página en blanco.</p><div className="mt-5 flex flex-wrap gap-2">{sectors.map(k=><button key={k} onClick={()=>setSector(k)} className={`rounded-full border px-3 py-2 text-[11px] font-bold ${sector===k?'border-blue-300 bg-blue-50 text-blue-700':'border-slate-200 bg-white text-slate-600'}`}>{k==='all'?'Todos los sectores':SECTOR_LABEL[k]||k}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{suggestions.map((t,i)=>{const active=solution?.id===t.id;return <button key={t.id} onClick={()=>onSelectSolution(t)} className={`overflow-hidden rounded-2xl border bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-md ${active?'border-blue-500 ring-2 ring-blue-100':'border-slate-200'}`}><div className={`grid aspect-[2.05/1] place-items-center bg-gradient-to-br ${['from-blue-50 to-cyan-100','from-indigo-50 to-slate-100','from-amber-50 to-blue-50','from-emerald-50 to-slate-100'][i%4]}`}><div className="flex h-20 w-32 items-end justify-center gap-2 rounded-2xl border border-white bg-white/75 p-3 shadow-sm"><span className="text-4xl">{['🏗️','🧰','🏢','🛠️','🏠','🚚'][i%6]}</span><div className="space-y-1 pb-1"><i className="block h-2 w-10 rounded bg-blue-200"/><i className="block h-2 w-14 rounded bg-slate-200"/><i className="block h-2 w-8 rounded bg-emerald-200"/></div></div></div><div className="p-4"><div className="flex items-center justify-between"><span className="text-[9px] font-bold uppercase text-slate-400">{SECTOR_LABEL[t.industry]||t.industry}</span>{active&&<span className="grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-[9px] font-black text-white">✓</span>}</div><h3 className="mt-2 text-sm font-black">{t.name}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{t.description}</p><div className="mt-3 flex gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-500">{t.stages?.length||0} pasos listos</span><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">Vista pública</span></div></div></button>})}</div></div>}

   {step===1&&<div className="max-w-4xl"><h1 className="text-3xl font-black tracking-tight">Datos de la operación</h1><p className="mt-2 text-sm text-slate-500">Ponle contexto a la estructura que TRACE ya preparó.</p><div className="mt-7 grid gap-5 md:grid-cols-2"><label className="md:col-span-2"><span className="text-xs font-black">Nombre del control o proyecto</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50" placeholder="Ej. Residencial Vista Real · Avance de obra"/></label><label><span className="text-xs font-black">Ubicación o referencia</span><input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Santo Domingo, RD"/></label><label><span className="text-xs font-black">Solución aplicada</span><div className="mt-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-800">{solution?.name||'Selecciona una solución'}</div></label></div><div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="text-xs font-black">Así empezará la operación</div><div className="mt-4 flex flex-wrap items-center gap-2">{(solution?.stages||[]).slice(0,6).map((s,i)=><div key={s.key||i} className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-white text-[9px] font-black text-blue-700 shadow-sm">{i+1}</span><span className="text-[10px] font-bold text-slate-600">{s.name}</span>{i<(solution?.stages||[]).slice(0,6).length-1&&<span className="text-slate-300">→</span>}</div>)}</div></div></div>}

   {step===2&&<div><h1 className="text-3xl font-black tracking-tight">¿Quiénes participarán?</h1><p className="mt-2 text-sm text-slate-500">Arrastra personas al equipo del control o selecciónalas con un clic.</p><div className="mt-6 grid gap-5 xl:grid-cols-[.9fr_1.1fr]">
    <section className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><div><div className="text-xs font-black">Personas disponibles</div><div className="text-[10px] text-slate-400">Arrastra desde aquí</div></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-slate-500">{available.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{available.map(u=><button draggable onDragStart={ev=>{ev.dataTransfer.setData('text/trace-participant',u.id);ev.dataTransfer.effectAllowed='copy'}} onClick={()=>toggleUser(u.id)} key={u.id} className="flex cursor-grab items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 text-left shadow-sm hover:border-blue-300 active:cursor-grabbing"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-900 text-[9px] font-black text-white">{initials(u.email)}</span><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-black">{u.email.split('@')[0]}</div><div className="truncate text-[9px] text-slate-400">{u.role||'Miembro'}</div></div><span className="text-slate-300">⠿</span></button>)}</div></section>
    <section onDragOver={ev=>ev.preventDefault()} onDrop={addByDrop} className="rounded-2xl border-2 border-dashed border-blue-200 bg-blue-50/60 p-4"><div className="flex items-center justify-between"><div><div className="text-xs font-black text-blue-950">Equipo de este control</div><div className="text-[10px] text-blue-600">Suelta personas aquí</div></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-blue-700">{selected.length}</span></div><div className="mt-4 min-h-[180px] space-y-2">{selected.map((u,i)=><div key={u.id} className="flex items-center gap-3 rounded-xl border border-blue-100 bg-white p-3 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-100 text-[10px] font-black text-blue-700">{initials(u.email)}</span><div className="min-w-0 flex-1"><div className="truncate text-[11px] font-black">{u.email.split('@')[0]}</div><div className="truncate text-[9px] text-slate-400">{i===0?'Responsable principal':'Participante'}</div></div><button onClick={()=>toggleUser(u.id)} className="grid h-7 w-7 place-items-center rounded-lg text-slate-400 hover:bg-red-50 hover:text-red-600">×</button></div>)}{!selected.length&&<div className="grid min-h-[150px] place-items-center text-center"><div><div className="text-3xl text-blue-300">⇢</div><div className="mt-2 text-[11px] font-black text-blue-800">Arrastra personas a este espacio</div><div className="mt-1 text-[9px] text-blue-500">También puedes hacer clic en una persona.</div></div></div>}</div></section>
   </div>{(options.departments||[]).length>0&&<div className="mt-5"><div className="text-xs font-black">Equipos o departamentos</div><div className="mt-3 flex flex-wrap gap-2">{options.departments.map(d=><button key={d.id} onClick={()=>toggleDepartment(d.id)} className={`rounded-xl border px-3 py-2 text-[10px] font-bold ${selectedDepartments.includes(d.id)?'border-blue-400 bg-blue-50 text-blue-700':'border-slate-200 bg-white text-slate-600'}`}>{d.name}</button>)}</div></div>}</div>}

   {step===3&&<div><h1 className="text-3xl font-black tracking-tight">Cómo se registrará</h1><p className="mt-2 text-sm text-slate-500">Revisa el arnés precargado y decide qué verá el cliente, propietario o inversionista.</p><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_340px]"><div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><div className="text-xs font-black">Etapas del control</div><span className="text-[9px] font-bold text-slate-400">Editables después</span></div><div className="mt-3 space-y-2">{(solution?.stages||[]).map((s,i)=><div key={s.key||i} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="text-slate-300">⠿</span><span className="grid h-7 w-7 place-items-center rounded-full bg-white text-[9px] font-black text-blue-700 shadow-sm">{i+1}</span><span className="flex-1 text-[11px] font-bold text-slate-700">{s.name}</span><span className="text-emerald-600">✓</span></div>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{['Fotos y evidencias','Incidencias y correcciones','Fechas límite','Aprobaciones','Listas de verificación','Historial y bitácora'].map(x=><div key={x} className="rounded-xl border border-slate-200 bg-white p-3 text-[11px] font-bold text-slate-700">✓ {x}</div>)}</div></div><div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-xs font-black">Vista pública</div><p className="mt-1 text-[10px] leading-4 text-slate-500">La información externa queda separada de notas, mensajes y datos internos.</p><div className="mt-3 space-y-2">{[['client','Cliente / inversionista'],['owner','Usuario / propietario'],['custom','Personalizada']].map(([k,l])=><button key={k} onClick={()=>{setAudience(k);setPublicView(true)}} className={`w-full rounded-xl border p-3 text-left ${audience===k?'border-blue-400 bg-blue-50':'border-slate-200'}`}><div className="text-[10px] font-black">{l}</div><div className="mt-1 text-[9px] text-slate-400">Avances, evidencias y estados autorizados.</div></button>)}</div><label className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-3 text-[10px] font-bold"><span>Preparar acceso compartido</span><input type="checkbox" checked={publicView} onChange={e=>setPublicView(e.target.checked)}/></label><div className="mt-4 flex items-center gap-3 rounded-xl border border-slate-100 p-3"><div className="grid h-16 w-16 place-items-center border-4 border-slate-900 bg-white text-[9px] font-black">QR</div><div><div className="text-[10px] font-black">Enlace + QR</div><div className="mt-1 text-[9px] text-slate-400">Se genera al activar el seguimiento.</div></div></div></div></div></div></div>}
  </main>
  <aside className="hidden border-l border-slate-200 bg-[#f7f9fc] p-5 lg:block"><div className="sticky top-0"><div className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Vista previa de estructura</div><div className="mt-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-black">{solution?.name||'Selecciona una solución'}</div><p className="mt-1 text-[10px] leading-4 text-slate-500">Así se organizará tu control.</p><div className="mt-4 space-y-2">{['Etapas y subetapas','Responsables y equipos','Evidencias y listas','Incidencias y correcciones','Vista pública para clientes'].map(x=><div key={x} className="flex items-center gap-2 text-[10px] font-semibold text-slate-600"><span className="grid h-6 w-6 place-items-center rounded-lg bg-blue-50 text-blue-700">✓</span>{x}</div>)}</div></div><div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="text-xs font-black text-blue-900">Con TRACE inicias más rápido</div><p className="mt-2 text-[10px] leading-5 text-blue-700">La solución ya trae los controles principales. Solo asignas personas y ajustas lo necesario.</p></div></div></aside></div>
  <footer className="flex items-center justify-between border-t border-slate-200 bg-white px-5 py-3"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold disabled:opacity-30">Volver</button><div className="flex items-center gap-3"><span className="text-[10px] text-slate-400">Paso {step+1} de 4</span>{step<3?<button disabled={!canNext||(!solution&&step===0)} onClick={()=>setStep(step+1)} className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">Continuar</button>:<button disabled={busy||!solution||!name.trim()} onClick={onCreate} className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{busy?'Activando…':'Activar TRACE'}</button>}</div></footer>
 </div></div></div>
}
