import { useMemo, useState } from "react";

function pct(v){return Math.max(0,Math.min(100,Number(v||0)))}

export default function TraceProjectDetail({data,people=[],departments=[],onBack,onOpenOperation,onAssign}){
 const [adding,setAdding]=useState(false),[type,setType]=useState('person'),[selected,setSelected]=useState(''),[role,setRole]=useState('member');
 if(!data?.project)return null;
 const p=data.project,ops=data.operations||[],assignedPeople=data.people||[],assignedDepartments=data.departments||[];
 const avg=ops.length?Math.round(ops.reduce((s,o)=>s+pct(o.completion_percentage),0)/ops.length):0;
 const available=useMemo(()=>type==='person'?people.filter(x=>!assignedPeople.some(a=>a.user_id===x.id)):departments.filter(x=>!assignedDepartments.some(a=>a.department_id===x.id)),[type,people,departments,assignedPeople,assignedDepartments]);
 async function add(e){e.preventDefault();if(!selected)return;await onAssign(p.id,type==='person'?{userId:selected,projectRole:role}:{departmentId:selected,projectRole:role});setSelected('');setAdding(false)}
 return <div className="mx-auto max-w-[1480px] space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><button onClick={onBack} className="text-xs font-black text-slate-500">← Proyectos</button><button onClick={()=>setAdding(true)} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">+ Asignar equipo</button></div>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-blue-600">Proyecto</div><h1 className="mt-2 text-3xl font-black">{p.name}</h1><p className="mt-2 text-sm text-slate-500">{p.location||'Sin ubicación'}{p.asset_code?` · ${p.asset_code}`:''}</p></div><div className="min-w-[260px]"><div className="flex justify-between text-xs"><span className="font-bold text-slate-500">Avance general</span><b>{avg}%</b></div><div className="mt-2 h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${avg}%`}}/></div></div></div></section>

  <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black">Controles del proyecto</h2><p className="text-xs text-slate-500">Entra solo cuando necesites revisar el seguimiento.</p></div><span className="text-xs font-black text-blue-600">{ops.length}</span></div>{ops.length?<div className="divide-y divide-slate-100">{ops.map(o=><button key={o.id} onClick={()=>onOpenOperation(o.id)} className="grid w-full gap-3 px-5 py-4 text-left hover:bg-slate-50 md:grid-cols-[1fr_130px_110px_auto] md:items-center"><div><div className="text-xs font-black text-slate-900">{o.title||o.process_name}</div><div className="mt-1 text-[10px] text-slate-400">{o.process_name} · {o.execution_code}</div></div><div><div className="flex justify-between text-[9px]"><span>Avance</span><b>{pct(o.completion_percentage)}%</b></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${pct(o.completion_percentage)}%`}}/></div></div><span className="text-[10px] font-bold text-slate-500">{String(o.status||'pendiente').replaceAll('_',' ')}</span><span className="text-lg text-slate-300">›</span></button>)}</div>:<div className="p-12 text-center text-sm text-slate-400">Este proyecto todavía no tiene controles activos.</div>}</div>

   <aside className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Equipo asignado</h2><p className="text-xs text-slate-500">Personas y departamentos del proyecto.</p></div><button onClick={()=>setAdding(true)} className="text-xs font-black text-blue-600">Agregar</button></div><div className="mt-4 space-y-2">{assignedPeople.map(x=><div key={x.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-900 text-[9px] font-black text-white">{x.email.slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{x.email.split('@')[0]}</div><div className="text-[9px] text-slate-400">{x.project_role}</div></div></div>)}{assignedDepartments.map(x=><div key={x.id} className="rounded-xl border border-blue-100 bg-blue-50 p-3"><div className="text-xs font-black text-blue-900">{x.name}</div><div className="mt-1 text-[9px] text-blue-600">{x.member_count||0} miembros · {x.project_role}</div></div>)}{!assignedPeople.length&&!assignedDepartments.length&&<div className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-xs text-slate-400">Todavía no hay equipo asignado.</div>}</div></aside>
  </section>

  {adding&&<div className="fixed inset-0 z-[110] grid place-items-center bg-slate-950/40 p-4"><form onSubmit={add} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Asignar al proyecto</h2><button type="button" onClick={()=>setAdding(false)}>×</button></div><div className="mt-5 inline-flex rounded-xl border border-slate-200 p-1"><button type="button" onClick={()=>{setType('person');setSelected('')}} className={`rounded-lg px-3 py-2 text-xs font-black ${type==='person'?'bg-blue-600 text-white':'text-slate-500'}`}>Persona</button><button type="button" onClick={()=>{setType('department');setSelected('')}} className={`rounded-lg px-3 py-2 text-xs font-black ${type==='department'?'bg-blue-600 text-white':'text-slate-500'}`}>Departamento</button></div><select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Selecciona</option>{available.map(x=><option key={x.id} value={x.id}>{type==='person'?x.email:x.name}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="member">Miembro</option><option value="supervisor">Supervisor</option><option value="manager">Responsable</option><option value="observer">Observador</option></select><button disabled={!selected} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40">Asignar</button></form></div>}
 </div>
}
