import{useMemo,useState}from'react';

const pct=v=>Math.max(0,Math.min(100,Number(v||0)));
const isDone=v=>['completed','approved','closed'].includes(String(v||'').toLowerCase());
const statusLabel=v=>({completed:'Completado',approved:'Aprobado',correction_required:'Requiere corrección',pending_approval:'Por confirmar',in_progress:'En curso',assigned:'Asignado',available:'Disponible',pending:'Por iniciar'})[v]||String(v||'Pendiente').replaceAll('_',' ');

export default function TraceOperationsCanvas({operations=[],onOpen,onNewControl}){
 const[filter,setFilter]=useState('active'),[query,setQuery]=useState('');
 const active=useMemo(()=>operations.filter(o=>!isDone(o.status)),[operations]);
 const completed=useMemo(()=>operations.filter(o=>isDone(o.status)),[operations]);
 const base=filter==='all'?operations:filter==='completed'?completed:active;
 const visible=useMemo(()=>base.filter(o=>!query||`${o.title||''} ${o.process_name||''} ${o.asset_name||''} ${o.execution_code||''}`.toLowerCase().includes(query.toLowerCase())),[base,query]);
 if(!operations.length)return <div className="grid min-h-[72vh] place-items-center"><div className="max-w-md text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-2xl font-black text-blue-600">✓</div><h1 className="mt-5 text-3xl font-black">Agrega tu primer control</h1><p className="mt-2 text-sm leading-6 text-slate-500">Elige una solución preparada y TRACE organizará las etapas, responsables y registros por ti.</p><button onClick={onNewControl} className="mt-6 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">+ Nuevo control</button></div></div>;
 return <div className="mx-auto max-w-[1350px] space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Operaciones</h1><p className="mt-1 text-sm text-slate-500">Controles que están funcionando ahora y los que ya terminaron.</p></div><button onClick={onNewControl} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-black text-white">+ Nuevo control</button></div><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="inline-flex w-fit rounded-xl border border-slate-200 bg-white p-1">{[['active',`Activos · ${active.length}`],['completed',`Completados · ${completed.length}`],['all',`Todos · ${operations.length}`]].map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-lg px-4 py-2 text-xs font-black ${filter===k?'bg-slate-950 text-white':'text-slate-500'}`}>{l}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full max-w-sm rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs outline-none focus:border-blue-400" placeholder="Buscar control o proyecto…"/></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-[1.4fr_.9fr_140px_130px_auto] gap-3 border-b bg-slate-50 px-5 py-3 text-[10px] font-black uppercase tracking-wide text-slate-400"><span>Control</span><span>Proyecto / recurso</span><span>Avance</span><span>Estado</span><span/></div>{visible.map(o=><button key={o.id} onClick={()=>onOpen(o.id)} className="grid w-full grid-cols-[1.4fr_.9fr_140px_130px_auto] items-center gap-3 border-b border-slate-100 px-5 py-4 text-left last:border-0 hover:bg-slate-50"><div><div className="text-xs font-black">{o.title||o.process_name}</div><div className="mt-1 text-[10px] text-slate-400">{o.execution_code}</div></div><span className="text-xs text-slate-500">{o.asset_name||'Sin proyecto'}</span><div><div className="flex justify-between text-[9px]"><span>Avance</span><b>{pct(o.completion_percentage)}%</b></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${pct(o.completion_percentage)}%`}}/></div></div><span className="text-[10px] font-bold text-slate-500">{statusLabel(o.status)}</span><span className="text-slate-300">›</span></button>)}{!visible.length&&<div className="p-12 text-center text-sm text-slate-400">No hay controles en esta vista.</div>}</div></div>;
}
