import {useEffect,useMemo,useState} from "react";
import TraceEvidencePage from "./TraceEvidencePage.jsx";
import {TRACE_ATTACHMENT_ACCEPT,humanAttachmentSupport,prepareTraceAttachment,validateTraceAttachment} from "../../utils/traceMedia.js";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
const auth=()=>{const t=localStorage.getItem("qr_token")||"";return t?{Authorization:`Bearer ${t}`}:{}};
async function api(path,options={}){const r=await fetch(`${BASE}${path}`,{...options,headers:{...auth(),...(options.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||`HTTP ${r.status}`);return d}
const categoryLabel=v=>({general:"General",documentation:"Documentación",refutation:"Refutación",correction:"Corrección",inspection:"Inspección",reference:"Referencia"}[v]||v);
const date=v=>v?new Date(v).toLocaleString("es-DO",{day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}):"—";

export default function TraceEvidenceWorkspacePage({projectId,executions=[],onNavigate}){
 const[mode,setMode]=useState("project");
 return <div className="space-y-4">
  <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2">
   <button onClick={()=>setMode("project")} className={`rounded-xl px-4 py-2.5 text-sm font-black ${mode==="project"?"bg-blue-600 text-white":"text-slate-600 hover:bg-slate-50"}`}>Evidencias</button>
   <button onClick={()=>setMode("library")} className={`rounded-xl px-4 py-2.5 text-sm font-black ${mode==="library"?"bg-blue-600 text-white":"text-slate-600 hover:bg-slate-50"}`}>Mi repositorio</button>
   <span className="ml-auto hidden items-center px-3 text-xs font-semibold text-slate-400 md:flex">Captura una vez · relaciona cuando haga falta</span>
  </div>
  {mode==="project"?<TraceEvidencePage projectId={projectId} executions={executions} onNavigate={onNavigate}/>:<EvidenceLibrary projectId={projectId} executions={executions}/>} 
 </div>
}

function EvidenceLibrary({projectId,executions}){
 const[data,setData]=useState({project:null,items:[]}),[ctx,setCtx]=useState({people:[],departments:[]}),[loading,setLoading]=useState(false),[error,setError]=useState(""),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[stages,setStages]=useState([]),[form,setForm]=useState({executionId:"",stageId:"",activityId:"",category:"documentation",title:"",notes:"",tags:"",userIds:[],departmentIds:[],file:null});
 const selectedStage=stages.find(s=>s.id===form.stageId),activities=selectedStage?.activities||[];
 async function load(){if(!projectId)return;setLoading(true);setError("");try{const[d,c]=await Promise.all([api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/evidence-library`),api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/evidence-library/context`)]);setData(d.data||{project:null,items:[]});setCtx(c.data||{people:[],departments:[]})}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function loadStages(executionId){setStages([]);if(!executionId)return;try{const d=await api(`/api/trace/v1/executions/${encodeURIComponent(executionId)}/stages/overview`);setStages(d.data?.stages||[])}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[projectId]);useEffect(()=>{loadStages(form.executionId)},[form.executionId]);
 const tags=useMemo(()=>form.tags.split(",").map(x=>x.trim()).filter(Boolean).slice(0,20),[form.tags]);
 function toggle(key,id){setForm(f=>({...f,[key]:f[key].includes(id)?f[key].filter(x=>x!==id):[...f[key],id]}))}
 async function openFile(item){setError("");try{const r=await fetch(`${BASE}${item.fileUrl}`,{headers:auth()});if(!r.ok)throw new Error(`No se pudo abrir el archivo (HTTP ${r.status}).`);const url=URL.createObjectURL(await r.blob()),w=window.open(url,"_blank","noopener,noreferrer");if(!w){URL.revokeObjectURL(url);throw new Error("El navegador bloqueó la apertura del archivo.")}setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setError(e.message)}}
 async function save(){if(!form.file)return setError("Selecciona un archivo para guardar la evidencia.");setBusy(true);setError("");try{const prepared=await prepareTraceAttachment(form.file),fd=new FormData();if(form.executionId)fd.set("executionId",form.executionId);if(form.stageId)fd.set("executionStageId",form.stageId);if(form.activityId)fd.set("executionActivityId",form.activityId);fd.set("category",form.category);fd.set("visibility","private");if(form.title.trim())fd.set("title",form.title.trim());if(form.notes.trim())fd.set("notes",form.notes.trim());fd.set("tags",JSON.stringify(tags));fd.set("mentionUserIds",JSON.stringify(form.userIds));fd.set("mentionDepartmentIds",JSON.stringify(form.departmentIds));fd.set("metadata",JSON.stringify(prepared.metadata||{}));fd.set("file",prepared.file);if(prepared.thumbnail)fd.set("thumbnail",prepared.thumbnail);await api(`/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/evidence-library`,{method:"POST",body:fd});setOpen(false);setForm({executionId:"",stageId:"",activityId:"",category:"documentation",title:"",notes:"",tags:"",userIds:[],departmentIds:[],file:null});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="mx-auto max-w-[1560px] space-y-5">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Repositorio privado</p><h1 className="mt-1 text-3xl font-black tracking-[-.035em] sm:text-4xl">Evidencias</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">Guarda documentación, respaldo, refutaciones o pruebas del proyecto sin obligarlas a nacer dentro de una actividad. Solo tú accedes al repositorio hasta que relaciones una evidencia con un contexto operativo.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">＋&nbsp;&nbsp;Guardar evidencia</button></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <div className="grid gap-3 sm:grid-cols-3"><Info label="Proyecto" value={data.project?.name||"Proyecto activo"}/><Info label="Propiedad" value="Solo quien la carga"/><Info label="Reutilización" value="Sin volver a subir el archivo"/></div>
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{loading?<div className="p-14 text-center text-sm text-slate-400">Cargando repositorio…</div>:!data.items?.length?<div className="p-14 text-center"><div className="text-lg font-black">Tu repositorio está vacío</div><p className="mt-1 text-sm text-slate-400">Guarda aquí una prueba que luego puedas invocar en incidencias, aprobaciones o correcciones.</p></div>:<div className="divide-y divide-slate-100">{data.items.map(item=><article key={item.id} className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_220px]"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-black text-blue-700">{categoryLabel(item.category)}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600">Privada</span>{item.links?.length>0&&<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">Usada en {item.links.length} contexto{item.links.length===1?"":"s"}</span>}</div><h3 className="mt-2 text-base font-black">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.stageName||item.executionTitle||"Contexto general del proyecto"}{item.activityTitle?` · ${item.activityTitle}`:""}</p>{item.notes&&<p className="mt-3 text-sm leading-6 text-slate-600">{item.notes}</p>}<div className="mt-3 flex flex-wrap gap-1.5">{(item.tags||[]).map(t=><span key={t} className="rounded-lg border border-slate-200 px-2 py-1 text-[10px] font-bold text-slate-500">#{t}</span>)}</div><p className="mt-3 text-[11px] text-slate-400">{date(item.createdAt)} · {item.originalFilename}</p></div><div className="flex items-center justify-end gap-2"><button type="button" onClick={()=>openFile(item)} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-black text-slate-700">Abrir archivo</button></div></article>)}</div>}</section>
  {open&&<div className="fixed inset-0 z-[90] overflow-y-auto bg-slate-950/55 p-3 sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><div className="mx-auto my-2 w-full max-w-5xl rounded-3xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 px-5 py-5 sm:px-7"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">{data.project?.name||"Proyecto"}</p><h2 className="mt-1 text-2xl font-black">Guardar evidencia</h2><p className="mt-1 text-sm text-slate-500">Añade contexto ahora. Después podrás usar el mismo archivo en otros procesos sin duplicarlo.</p></div><button disabled={busy} onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-xl">×</button></div><div className="space-y-6 p-5 sm:p-7">
    <section><Step n="1" title="Contexto"/><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Trabajo" help="Opcional. Déjalo vacío si es documentación general del proyecto."><select className="control" value={form.executionId} onChange={e=>setForm(f=>({...f,executionId:e.target.value,stageId:"",activityId:""}))}><option value="">Contexto general del proyecto</option>{executions.map(e=><option key={e.id} value={e.id}>{e.title||e.execution_code}</option>)}</select></Field><Field label="Etapa" help="Opcional. Ubica la evidencia dentro del proceso."><select disabled={!form.executionId} className="control disabled:bg-slate-50" value={form.stageId} onChange={e=>setForm(f=>({...f,stageId:e.target.value,activityId:""}))}><option value="">Sin etapa específica</option>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Actividad" help="Opcional. Solo selecciónala si esta prueba demuestra una actividad concreta."><select disabled={!form.stageId} className="control disabled:bg-slate-50" value={form.activityId} onChange={e=>setForm(f=>({...f,activityId:e.target.value}))}><option value="">Sin actividad específica</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></Field><Field label="Tipo de contexto"><select className="control" value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value}))}><option value="documentation">Documentación</option><option value="refutation">Refutación</option><option value="correction">Corrección</option><option value="inspection">Inspección</option><option value="reference">Referencia</option><option value="general">General</option></select></Field></div></section>
    <section><Step n="2" title="Descripción y etiquetas"/><div className="mt-3 grid gap-4 md:grid-cols-2"><Field label="Nombre"><input className="control" value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="Ej. Informe del proveedor"/></Field><Field label="Etiquetas" help="Sepáralas por coma."><input className="control" value={form.tags} onChange={e=>setForm(f=>({...f,tags:e.target.value}))} placeholder="pintura, proveedor, apartamento 304"/></Field></div><Field label="Notas" help="Explica qué demuestra o por qué conviene conservar esta evidencia."><textarea className="control min-h-28 resize-y" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Contexto de la evidencia…"/></Field></section>
    {(ctx.people?.length>0||ctx.departments?.length>0)&&<section><Step n="3" title="Mencionar"/><p className="mt-1 text-xs text-slate-500">Las menciones conservan el contexto. No convierten la evidencia en pública.</p><div className="mt-3 grid gap-4 md:grid-cols-2"><MentionBox title="Miembros" items={ctx.people||[]} selected={form.userIds} getLabel={x=>x.email} onToggle={id=>toggle("userIds",id)}/><MentionBox title="Departamentos" items={ctx.departments||[]} selected={form.departmentIds} getLabel={x=>x.name} onToggle={id=>toggle("departmentIds",id)}/></div></section>}
    <section><Step n="4" title="Archivo"/><label className="mt-3 block cursor-pointer rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-6 hover:border-blue-400"><div className="flex items-center justify-between gap-4"><div><div className="font-black text-slate-800">{form.file?form.file.name:"Seleccionar archivo"}</div><div className="mt-1 text-xs text-slate-500">Foto, documento o audio</div></div><span className="rounded-xl bg-white px-4 py-2 text-xs font-black text-blue-600 shadow-sm">Examinar</span></div><input type="file" accept={TRACE_ATTACHMENT_ACCEPT} className="sr-only" onChange={e=>{const file=e.target.files?.[0]||null;if(file){const check=validateTraceAttachment(file);if(!check.ok){setError(check.message);e.target.value="";return}}setForm(f=>({...f,file}))}}/></label><p className="mt-2 text-[11px] leading-5 text-slate-400">{humanAttachmentSupport()}</p></section>
   </div><div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 sm:px-7"><p className="max-w-xl text-xs text-slate-400">Privada por defecto. Compartirla después crea una referencia al mismo archivo, no otra copia.</p><div className="flex gap-2"><button disabled={busy} onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Cancelar</button><button disabled={busy||!form.file} onClick={save} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white disabled:bg-slate-300">{busy?"Guardando…":"Guardar evidencia"}</button></div></div></div></div>}
 </div>
}

function Info({label,value}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-slate-800">{value}</p></div>}
function Step({n,title}){return <div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-600 text-xs font-black text-white">{n}</span><h3 className="font-black text-slate-900">{title}</h3></div>}
function Field({label,help,children}){return <label className="block"><span className="text-xs font-black text-slate-700">{label}</span>{help&&<span className="ml-2 text-[11px] text-slate-400">{help}</span>}<div className="mt-2">{children}</div></label>}
function MentionBox({title,items,selected,getLabel,onToggle}){return <div className="rounded-2xl border border-slate-200 p-3"><p className="mb-2 text-xs font-black text-slate-600">{title}</p><div className="max-h-36 space-y-1 overflow-y-auto">{items.map(x=><label key={x.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 text-xs hover:bg-slate-50"><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>onToggle(x.id)}/><span className="truncate">{getLabel(x)}</span></label>)}</div></div>}
