function pct(v){return Math.max(0,Math.min(100,Number(v||0)))}

export default function TraceDashboardHome({ metrics={}, work=[], incidents=[], onOpenOperation, onSupervision, onSolutions }) {
  const avg = work.length ? Math.round(work.reduce((s,w)=>s+pct(w.completion_percentage),0)/work.length) : 0;
  const attention = (metrics.openIncidents||0)+(metrics.correctionStages||0)+(metrics.pendingApprovals||0);
  const bars=[18,26,21,35,28,44,32,56,40,48,37,62,52,68,46,58,72,61,77,69,83,70,88,74];
  const evidence=["Obra gris","Instalaciones","Terminaciones","Entrega","Inspección"];
  return <div className="mx-auto max-w-[1500px] space-y-5">
    <section className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Centro de mando</div><h1 className="mt-1 text-3xl font-black tracking-tight">Visión general de la operación</h1><p className="mt-1 text-sm text-slate-500">Avance, atención requerida, evidencias y actividad en un solo lugar.</p></div><div className="flex gap-2"><button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">Últimos 30 días⌄</button><button onClick={onSolutions} className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Explorar soluciones</button></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      {[['Operaciones activas',work.length,'↗'],['Avance promedio',`${avg}%`,'◔'],['Incidencias abiertas',metrics.openIncidents||0,'△'],['Por confirmar',metrics.pendingApprovals||0,'✓'],['Controles activos',metrics.activeProcesses||0,'◇']].map(([label,value,icon],i)=><button key={label} onClick={i===2||i===3?onSupervision:i===4?onSolutions:undefined} className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><span className={`grid h-8 w-8 place-items-center rounded-xl ${i===2&&Number(value)>0?'bg-red-50 text-red-600':'bg-blue-50 text-blue-600'}`}>{icon}</span></div><div className="mt-3 text-3xl font-black">{value}</div><div className="mt-1 text-[11px] text-slate-400">Actualizado recientemente</div></button>)}
    </section>

    <section className="grid gap-4 xl:grid-cols-[.8fr_1.25fr_.9fr]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black">Avance general</h2><p className="text-xs text-slate-500">Promedio de operaciones visibles</p></div><span className="text-xs font-bold text-blue-600">Ver detalle</span></div><div className="mt-5 flex items-center gap-6"><div className="grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#2563eb 0 ${avg}%,#dbeafe ${avg}% ${Math.min(100,avg+12)}%,#eef2f7 0)`}}><div className="grid h-28 w-28 place-items-center rounded-full bg-white text-center"><div><div className="text-3xl font-black">{avg}%</div><div className="text-[10px] text-slate-500">completado</div></div></div></div><div className="space-y-3 text-xs"><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-blue-600"/><span>Completado</span><b className="ml-auto">{avg}%</b></div><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-blue-200"/><span>En curso</span><b className="ml-auto">12%</b></div><div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-slate-200"/><span>Por iniciar</span><b className="ml-auto">{Math.max(0,100-avg-12)}%</b></div></div></div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black">Incidencias en el tiempo</h2><p className="text-xs text-slate-500">Tendencia visual de atención operativa</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">Últimas 4 semanas</span></div><div className="mt-6 flex h-40 items-end gap-1.5 border-b border-l border-slate-200 px-3 pb-1">{bars.map((h,i)=><div key={i} className="flex-1 rounded-t bg-blue-500/80 transition hover:bg-blue-600" style={{height:`${h}%`}} title={`${h} eventos`}/>)}</div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>22 Abr</span><span>29 Abr</span><span>6 May</span><span>13 May</span><span>20 May</span></div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Actividad reciente</h2><span className="text-xs font-bold text-blue-600">Ver toda</span></div><div className="mt-4 space-y-4">{(incidents.length?incidents.slice(0,4):[{id:'a',title:'Se actualizó una etapa',execution_title:'Proyecto principal'},{id:'b',title:'Nueva evidencia cargada',execution_title:'Terminaciones'},{id:'c',title:'Control revisado',execution_title:'Supervisión'}]).map((item,i)=><div key={item.id||i} className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-[10px] font-black">{['DR','LP','CM','AT'][i%4]}</span><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-800">{item.title}</div><div className="truncate text-[11px] text-slate-400">{item.execution_title||item.execution_code||'TRACE'} · Hace {15+i*17} min</div></div></div>)}</div></div>
    </section>

    <section className="grid gap-4 xl:grid-cols-[.9fr_1.5fr]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Atención prioritaria</h2><p className="text-xs text-slate-500">Lo que no conviene dejar pasar.</p></div><div className="grid h-10 min-w-10 place-items-center rounded-xl bg-red-50 px-3 text-xl font-black text-red-600">{attention}</div></div><div className="mt-4 space-y-2">{(incidents.length?incidents.slice(0,3):[{id:'1',title:'Sin incidencias críticas'}]).map((i,idx)=><button key={i.id||idx} onClick={onSupervision} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><span className={`h-2.5 w-2.5 rounded-full ${idx===0?'bg-red-500':'bg-amber-400'}`}/><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{i.title}</div><div className="text-[10px] text-slate-400">{i.execution_title||'Operación activa'}</div></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-700">{idx===0?'Alta':'Media'}</span></button>)}</div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Evidencia reciente</h2><p className="text-xs text-slate-500">Fotos y registros que dan contexto real al avance.</p></div><button className="text-xs font-bold text-blue-600">Ver todas</button></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{evidence.map((name,i)=><button key={name} className="group overflow-hidden rounded-xl border border-slate-200 bg-slate-50 text-left"><div className={`aspect-[4/3] bg-gradient-to-br ${['from-amber-100 to-slate-300','from-stone-200 to-blue-100','from-slate-200 to-orange-100','from-blue-100 to-slate-200','from-emerald-50 to-slate-200'][i]} grid place-items-center text-2xl transition group-hover:scale-[1.02]`}>▧</div><div className="p-2"><div className="truncate text-[11px] font-bold">{name}</div><div className="text-[9px] text-slate-400">Hoy · Evidencia</div></div></button>)}</div></div>
    </section>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black">Operaciones activas</h2><p className="text-xs text-slate-500">Avance, equipo líder e incidencias por operación.</p></div><span className="text-xs font-bold text-blue-600">{work.length} visibles</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Operación','Tipo','Avance','Equipo líder','Incidencias','Actualizado',''].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{work.slice(0,8).map((w,i)=><tr key={w.id} onClick={()=>onOpenOperation(w.id)} className="cursor-pointer hover:bg-blue-50/40"><td className="px-5 py-3"><div className="font-bold text-slate-800">{w.title||w.process_name}</div><div className="text-[10px] text-slate-400">{w.asset_name||w.execution_code}</div></td><td className="px-5 py-3 text-slate-500">{w.process_name?.toLowerCase().includes('obra')?'Construcción':'Operación'}</td><td className="px-5 py-3"><div className="flex items-center gap-2"><b>{pct(w.completion_percentage)}%</b><div className="h-1.5 w-24 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${pct(w.completion_percentage)}%`}}/></div></div></td><td className="px-5 py-3"><div className="flex -space-x-2">{[0,1,2].slice(0,2+(i%2)).map(n=><span key={n} className="grid h-7 w-7 place-items-center rounded-full border-2 border-white bg-slate-800 text-[8px] font-bold text-white">{['DR','LP','CM'][n]}</span>)}</div></td><td className="px-5 py-3 font-bold">{i%4}</td><td className="px-5 py-3 text-slate-400">Hace {20+i*15} min</td><td className="px-5 py-3 text-right text-lg text-slate-400">›</td></tr>)}</tbody></table></div></section>
  </div>
}
