function pct(v){return Math.max(0,Math.min(100,Number(v||0)))}
function statusBucket(v){if(['approved','completed'].includes(v))return'completed';if(['in_progress','assigned','available'].includes(v))return'progress';if(['correction_required','blocked','overdue'].includes(v))return'attention';return'pending'}

function MiniBars({values=[]}){const max=Math.max(1,...values);return <div className="flex h-36 items-end gap-2 border-b border-l border-slate-200 px-3 pb-1">{values.map((v,i)=><div key={i} className="group relative flex-1"><div className="w-full rounded-t bg-blue-500 transition group-hover:bg-blue-700" style={{height:`${Math.max(8,(v/max)*100)}%`}}/><span className="pointer-events-none absolute -top-6 left-1/2 hidden -translate-x-1/2 rounded bg-slate-950 px-1.5 py-1 text-[9px] font-bold text-white group-hover:block">{v}</span></div>)}</div>}

export default function TraceDashboardHome({ metrics={}, work=[], incidents=[], onOpenOperation, onSupervision, onSolutions }) {
  const avg=work.length?Math.round(work.reduce((s,w)=>s+pct(w.completion_percentage),0)/work.length):0;
  const attention=(metrics.openIncidents||0)+(metrics.correctionStages||0)+(metrics.pendingApprovals||0);
  const status=work.reduce((a,w)=>{const k=statusBucket(w.status);a[k]=(a[k]||0)+1;return a},{completed:0,progress:0,attention:0,pending:0});
  const opBars=(work.length?work.slice(0,8):[{completion_percentage:0}]).map(w=>pct(w.completion_percentage));
  const evidenceLabels=['Fotos','Documentos','Inspecciones','Entregas','Correcciones'];
  return <div className="mx-auto max-w-[1560px] space-y-5">
    <section className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Centro de mando</div><h1 className="mt-1 text-3xl font-black tracking-tight">Visión general de la operación</h1><p className="mt-1 text-sm text-slate-500">Avance, atención requerida, evidencias y actividad desde una sola vista.</p></div><div className="flex gap-2"><button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">Estado actual</button><button onClick={onSolutions} className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Explorar soluciones</button></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
      ['Operaciones activas',work.length,'▦'],['Avance promedio',`${avg}%`,'◔'],['Incidencias abiertas',metrics.openIncidents||0,'△'],['Por confirmar',metrics.pendingApprovals||0,'✓'],['Controles activos',metrics.activeProcesses||0,'◇']
    ].map(([label,value,icon],i)=><button key={label} onClick={i===2||i===3?onSupervision:i===4?onSolutions:undefined} className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><span className={`grid h-8 w-8 place-items-center rounded-xl ${i===2&&Number(value)>0?'bg-red-50 text-red-600':'bg-blue-50 text-blue-600'}`}>{icon}</span></div><div className="mt-3 text-3xl font-black">{value}</div><div className="mt-1 text-[11px] text-slate-400">Datos actuales del espacio</div></button>)}</section>

    <section className="grid gap-4 xl:grid-cols-[.82fr_1.18fr_.9fr]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black">Estado de las operaciones</h2><p className="text-xs text-slate-500">Distribución actual por estado</p></div><span className="text-xs font-bold text-blue-600">{work.length} activas</span></div><div className="mt-5 flex items-center gap-6"><div className="grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#2563eb 0 ${avg}%,#93c5fd ${avg}% ${Math.min(100,avg+12)}%,#e5e7eb 0)`}}><div className="grid h-28 w-28 place-items-center rounded-full bg-white text-center"><div><div className="text-3xl font-black">{avg}%</div><div className="text-[10px] text-slate-500">avance promedio</div></div></div></div><div className="min-w-0 flex-1 space-y-3 text-xs">{[['En curso',status.progress,'bg-blue-600'],['Requieren atención',status.attention,'bg-amber-400'],['Completadas',status.completed,'bg-emerald-500'],['Por iniciar',status.pending,'bg-slate-300']].map(([l,v,c])=><div key={l} className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${c}`}/><span className="truncate">{l}</span><b className="ml-auto">{v}</b></div>)}</div></div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black">Avance por operación</h2><p className="text-xs text-slate-500">Comparación de las operaciones visibles</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700">Actual</span></div><div className="mt-6"><MiniBars values={opBars}/><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>0%</span><span>50%</span><span>100%</span></div></div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Actividad reciente</h2><button onClick={onSupervision} className="text-xs font-bold text-blue-600">Ver toda</button></div><div className="mt-4 space-y-4">{(incidents.length?incidents.slice(0,4):[{id:'a',title:'Sin incidencias nuevas',execution_title:'Operación estable'}]).map((item,i)=><button key={item.id||i} onClick={onSupervision} className="flex w-full gap-3 text-left"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-[10px] font-black">{['DR','LP','CM','AT'][i%4]}</span><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-800">{item.title}</div><div className="truncate text-[11px] text-slate-400">{item.execution_title||item.execution_code||'TRACE'}</div></div></button>)}</div></div>
    </section>

    <section className="grid gap-4 xl:grid-cols-[.92fr_1.35fr]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Atención prioritaria</h2><p className="text-xs text-slate-500">Revisión, corrección o confirmación.</p></div><div className="grid h-10 min-w-10 place-items-center rounded-xl bg-red-50 px-3 text-xl font-black text-red-600">{attention}</div></div><div className="mt-4 space-y-2">{(incidents.length?incidents.slice(0,4):[{id:'1',title:'Sin incidencias críticas'}]).map((i,idx)=><button key={i.id||idx} onClick={onSupervision} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><span className={`h-2.5 w-2.5 rounded-full ${idx===0?'bg-red-500':'bg-amber-400'}`}/><div className="min-w-0 flex-1"><div className="truncate text-xs font-bold">{i.title}</div><div className="text-[10px] text-slate-400">{i.execution_title||'Operación activa'}</div></div><span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-700">{idx===0?'Alta':'Media'}</span></button>)}</div></div>

      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Evidencias y registros</h2><p className="text-xs text-slate-500">Accesos visuales a los registros más usados.</p></div><button className="text-xs font-bold text-blue-600">Ver evidencias</button></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{evidenceLabels.map((name,i)=><button key={name} className="group overflow-hidden rounded-xl border border-slate-200 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-md"><div className={`grid aspect-[4/3] place-items-center bg-gradient-to-br ${['from-blue-50 to-cyan-100','from-amber-50 to-orange-100','from-emerald-50 to-teal-100','from-violet-50 to-blue-100','from-rose-50 to-amber-100'][i]}`}><svg viewBox="0 0 120 80" className="h-16 w-24 opacity-80"><rect x="16" y="18" width="88" height="50" rx="8" fill="white" stroke="#94a3b8"/><rect x="27" y="30" width="30" height="24" rx="4" fill="#dbeafe"/><path d="M29 51l9-9 7 7 6-5 8 10" fill="none" stroke="#2563eb" strokeWidth="3"/><circle cx="78" cy="35" r="8" fill="#bfdbfe"/><path d="M69 56h23" stroke="#94a3b8" strokeWidth="4" strokeLinecap="round"/></svg></div><div className="p-2.5"><div className="truncate text-[11px] font-black">{name}</div><div className="text-[9px] text-slate-400">Abrir módulo</div></div></button>)}</div></div>
    </section>

    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-black">Operaciones activas</h2><p className="text-xs text-slate-500">Avance, estado y contexto por operación.</p></div><span className="text-xs font-bold text-blue-600">{work.length} visibles</span></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Operación','Tipo','Avance','Estado','Incidencias','Actualizado',''].map(h=><th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{work.slice(0,8).map((w,i)=><tr key={w.id} onClick={()=>onOpenOperation(w.id)} className="cursor-pointer hover:bg-blue-50/40"><td className="px-5 py-3"><div className="font-bold text-slate-800">{w.title||w.process_name}</div><div className="text-[10px] text-slate-400">{w.asset_name||w.execution_code}</div></td><td className="px-5 py-3 text-slate-500">{w.process_name?.toLowerCase().includes('obra')?'Construcción':'Operación'}</td><td className="px-5 py-3"><div className="flex items-center gap-2"><b>{pct(w.completion_percentage)}%</b><div className="h-1.5 w-24 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${pct(w.completion_percentage)}%`}}/></div></div></td><td className="px-5 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-600">{String(w.status||'pendiente').replaceAll('_',' ')}</span></td><td className="px-5 py-3 font-bold">{incidents.filter(x=>x.execution_id===w.id).length}</td><td className="px-5 py-3 text-slate-400">En seguimiento</td><td className="px-5 py-3 text-right text-lg text-slate-400">›</td></tr>)}</tbody></table></div></section>
  </div>
}
