import {useEffect,useMemo,useRef,useState} from "react";
import QRCode from "qrcode";

const STATUS={completed:"Completada",in_progress:"En curso",pending_approval:"Pendiente de aprobación",attention:"Requiere atención",available:"Disponible",not_started:"No iniciada"};
const fmtDate=v=>v?new Date(v).toLocaleDateString("es-DO",{day:"2-digit",month:"short",year:"numeric"}):"Sin fecha";
const fmtDue=v=>v?new Date(v).toLocaleString("es-DO",{day:"2-digit",month:"short",hour:"numeric",minute:"2-digit"}):"Sin fecha límite";
const initials=v=>String(v||"U").split(/[@.\s_-]+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"U";
const eventTone=t=>{const s=String(t||"");if(s.includes("incident"))return"bg-red-500";if(s.includes("evidence"))return"bg-emerald-500";if(s.includes("approval"))return"bg-violet-500";return"bg-blue-600"};
const healthTone={on_track:"border-emerald-200 bg-emerald-50 text-emerald-800",attention:"border-amber-200 bg-amber-50 text-amber-900",at_risk:"border-red-200 bg-red-50 text-red-800",completed:"border-blue-200 bg-blue-50 text-blue-800"};

export default function TraceProjectSummaryDashboard({data,period,setPeriod,onRegister,onShare,onNavigate,onOpenIncident}){
 const project=data?.project||{},metrics=data?.metrics||{},stages=data?.stages||[],alerts=data?.alerts||[],nextActions=data?.nextActions||[],activities=data?.activities||[];
 const publicUrl=project.publicPath?`${window.location.origin}${project.publicPath}`:"";
 const qrRef=useRef(null);const[copied,setCopied]=useState(false);
 useEffect(()=>{if(publicUrl&&qrRef.current)QRCode.toCanvas(qrRef.current,publicUrl,{width:92,margin:1,errorCorrectionLevel:"M"}).catch(()=>{})},[publicUrl]);
 async function copy(){if(!publicUrl)return;try{await navigator.clipboard.writeText(publicUrl);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{}}
 function shareLink(){if(!publicUrl)return;if(navigator.share){navigator.share({title:project.name||"Seguimiento Trace",url:publicUrl}).catch(()=>{})}else onShare?.()}
 const statusLabel=project.status==="active"?"Activo":project.status==="completed"?"Finalizado":project.status==="paused"?"En pausa":project.status||"Proyecto";
 const healthClass=healthTone[project.health]||healthTone.on_track;
 const stageStatusClass=s=>s==="attention"?"text-red-600":s==="completed"?"text-emerald-600":s==="pending_approval"?"text-amber-600":s==="in_progress"?"text-blue-600":"text-slate-400";
 return <div className="mx-auto max-w-[1560px] space-y-5">
  <header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
   <div><div className="text-sm text-slate-500">Trace&nbsp;&nbsp;/&nbsp;&nbsp;<span className="text-slate-700">Resumen</span></div><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-4xl font-black tracking-[-.04em]">{project.name||"Proyecto"}</h1><span className={`rounded-full px-3 py-1 text-xs font-black ${project.status==="active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{statusLabel}</span></div><p className="mt-2 text-sm font-semibold text-slate-600">{project.description||"Seguimiento del proyecto"}</p><p className="mt-1 text-sm text-slate-400">{fmtDate(project.startedAt)} – {fmtDate(project.dueAt)}</p></div>
   <div className="flex flex-wrap gap-3"><select value={period} onChange={e=>setPeriod(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold"><option value="today">Hoy</option><option value="week">Esta semana</option><option value="month">Este mes</option></select><button onClick={onShare} disabled={!project.publicPath} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-black disabled:opacity-40">↗&nbsp;&nbsp;Compartir seguimiento</button><button onClick={onRegister} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-100">＋&nbsp;&nbsp;Registrar actividad</button></div>
  </header>

  <section className={`rounded-2xl border p-5 ${healthClass}`}><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-black uppercase tracking-[.14em] opacity-70">Estado del proyecto</div><div className="mt-1 text-xl font-black">{project.healthLabel||"En orden"}</div><p className="mt-1 text-sm opacity-90">{project.healthReason||"El proyecto avanza sin alertas importantes."}</p></div>{project.health!=="on_track"&&project.health!=="completed"&&<button onClick={()=>onNavigate?.("incidents")} className="rounded-xl border border-current/20 bg-white/60 px-4 py-2 text-xs font-black">Revisar atención →</button>}</div></section>

  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric title="Avance general" value={`${metrics.progress||0}%`} tone="blue" onClick={()=>onNavigate?.("stages")}/><Metric title="Actividades en curso" value={metrics.inProgress||0} tone="blue" onClick={()=>onNavigate?.("activities")}/><Metric title="Actividades atrasadas" value={metrics.overdue||0} tone="red" onClick={()=>onNavigate?.("activities")}/><Metric title="Incidencias abiertas" value={metrics.openIncidents||0} tone="red" onClick={()=>onNavigate?.("incidents")}/><Metric title="Pendientes de aprobación" value={metrics.pendingApprovals||0} tone="orange" onClick={()=>onNavigate?.("incidents")}/></section>

  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Progreso por etapas</h2><p className="mt-1 text-xs text-slate-500">Avance según actividades completadas.</p></div><button onClick={()=>onNavigate?.("stages")} className="text-xs font-black text-blue-600">Ver etapas →</button></div><div className="mt-4 divide-y divide-slate-100">{stages.map(s=><button key={s.id} onClick={()=>onNavigate?.("stages")} className="grid w-full gap-3 py-4 text-left md:grid-cols-[1fr_150px_170px] md:items-center"><div><div className="flex items-center gap-2"><b className="text-sm">{s.name}</b><span className={`text-[10px] font-black ${stageStatusClass(s.status)}`}>{STATUS[s.status]||s.status}</span></div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-slate-400"><span>{s.responsibles?.[0]?`Responsable: ${s.responsibles[0]}`:"Responsable sin asignar"}</span><span>{s.pendingActivities||0} pendientes</span><span>{s.openIncidents||0} incidencias</span></div></div><div><div className="flex justify-between text-xs"><span className="text-slate-400">Avance</span><b className="text-blue-600">{s.progress||0}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-blue-600" style={{width:`${Math.max(0,Math.min(100,s.progress||0))}%`}}/></div></div><div className="text-right text-xs font-semibold text-slate-400">{STATUS[s.status]||"No iniciada"} ›</div></button>)}{!stages.length&&<div className="py-10 text-center text-sm text-slate-400">No hay etapas configuradas.</div>}</div></section>

   <div className="space-y-5">
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">Alertas prioritarias</h2></div><div className="divide-y divide-slate-100">{alerts.map(a=><button key={a.type} onClick={()=>onNavigate?.(a.type==="incidents"||a.type==="approvals"?"incidents":"activities")} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-slate-50"><span className={`text-xl ${a.type==="incidents"?"text-red-500":"text-orange-500"}`}>△</span><span className="min-w-0 flex-1"><b className="block text-sm">{a.label}</b><span className="mt-1 block text-[11px] text-blue-600">{a.action||"Revisar"}</span></span><span>›</span></button>)}{!alerts.length&&<div className="p-8 text-center text-sm text-slate-400">Sin alertas prioritarias.</div>}</div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-black">Próximas acciones</h2><p className="mt-1 text-[11px] text-slate-400">{data?.viewer?.scope==="own"?"Tus actividades próximas":"Acciones próximas del proyecto"}</p></div><div className="divide-y divide-slate-100">{nextActions.slice(0,5).map(x=><div key={x.id} className="flex gap-3 px-5 py-4"><span className="mt-1 h-4 w-4 shrink-0 rounded border border-slate-400"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{x.title||x.execution_code}</b><span className="mt-1 block text-[11px] text-slate-400">{x.process_name||x.execution_code}</span><span className="mt-1 block text-[11px] text-slate-500">{x.assigned_email?`Responsable: ${x.assigned_email} · `:""}{fmtDue(x.due_at)}</span></div></div>)}{!nextActions.length&&<div className="p-8 text-center text-sm text-slate-400">No hay acciones próximas con fecha límite.</div>}</div></section>
   </div>
  </div>

  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
   <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-black">Actividad reciente</h2><button onClick={()=>onNavigate?.("activities")} className="text-xs font-black text-blue-600">Ver todas las actividades →</button></div><div className="divide-y divide-slate-100">{activities.slice(0,5).map(a=><div key={a.id} className="flex items-start gap-4 px-5 py-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-[10px] font-black">{initials(a.actor_email||a.actor_role)}</span><span className={`mt-3 h-2.5 w-2.5 shrink-0 rounded-full ${eventTone(a.event_type)}`}/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{a.description||a.event_type}</b><span className="mt-1 block text-[11px] text-slate-400">{a.actor_email||a.actor_role||"Trace"}{a.stage_name?` · ${a.stage_name}`:""}</span></div><span className="whitespace-nowrap text-[11px] text-slate-400">{a.occurred_at?new Date(a.occurred_at).toLocaleString("es-DO",{day:"2-digit",month:"short",hour:"numeric",minute:"2-digit"}):""}</span></div>)}{!activities.length&&<div className="p-10 text-center text-sm text-slate-400">Todavía no hay movimientos recientes.</div>}</div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-black">Acceso al seguimiento</h2><div className="mt-2 flex items-center gap-2 text-xs"><span className={`h-2.5 w-2.5 rounded-full ${publicUrl?"bg-emerald-500":"bg-slate-300"}`}/><span className="font-semibold text-slate-600">{publicUrl?"QR y enlace activos":"Acceso público no disponible"}</span></div></div>{publicUrl&&<canvas ref={qrRef} className="h-[92px] w-[92px] rounded-lg border border-slate-100"/>}</div><div className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-xs text-slate-500 break-all">{publicUrl||"El enlace se generará al activar la vista compartida."}</div><div className="mt-4 grid grid-cols-3 gap-2"><button disabled={!publicUrl} onClick={()=>publicUrl&&window.open(publicUrl,"_blank","noopener,noreferrer")} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black disabled:opacity-40">Ver QR</button><button disabled={!publicUrl} onClick={copy} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black disabled:opacity-40">{copied?"Copiado":"Copiar enlace"}</button><button disabled={!publicUrl} onClick={shareLink} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-black text-white disabled:bg-slate-300">Compartir</button></div></section>
  </div>
 </div>
}
function Metric({title,value,tone="blue",onClick}){const color=tone==="red"?"text-red-500":tone==="orange"?"text-orange-500":"text-blue-600";return <button onClick={onClick} className="rounded-2xl border border-slate-200 bg-white p-5 text-left hover:border-blue-300"><div className="text-xs font-semibold text-slate-500">{title}</div><div className={`mt-2 text-3xl font-black ${color}`}>{value}</div></button>}
