import {useEffect,useMemo,useState} from "react";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
function headers(json=false){const t=localStorage.getItem("qr_token")||"";return{...(json?{"Content-Type":"application/json"}:{}),...(t?{Authorization:`Bearer ${t}`}:{})}}
const closed=s=>["resolved","validated","closed"].includes(String(s||""));
const statusLabel=s=>({open:"Abierta",assigned:"Asignada",in_progress:"En corrección",in_review:"Pendiente de decisión",on_hold:"En espera",resolved:"Resuelta",validated:"Validada",closed:"Cerrada",reopened:"Observada"})[s]||String(s||"Pendiente").replaceAll("_"," ");
const severityLabel=s=>({critical:"Crítica",high:"Alta",medium:"Media",low:"Baja"})[s]||s;
const date=v=>v?new Date(v).toLocaleDateString("es-DO",{day:"2-digit",month:"short",year:"numeric"}):"Sin fecha";
const initials=v=>String(v||"—").split(/[@.\s_-]+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"—";
const toneSeverity=s=>s==="critical"?"bg-red-100 text-red-700":s==="high"?"bg-rose-50 text-rose-700":s==="medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600";
const toneStatus=s=>s==="in_review"?"bg-violet-50 text-violet-700":s==="in_progress"?"bg-amber-50 text-amber-700":closed(s)?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700";

export default function TraceIncidentsPage({projectId,onReport,onDecision}){
 const[stage,setStage]=useState(""),[sort,setSort]=useState("recent"),[data,setData]=useState({metrics:{},items:[],stages:[]}),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState(null),[showHistory,setShowHistory]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){if(!projectId)return;setLoading(true);setError("");try{const p=new URLSearchParams();if(stage)p.set("stage",stage);p.set("sort",sort);const r=await fetch(`${BASE}/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/incidents?${p}`,{headers:headers()});const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||`HTTP ${r.status}`);setData(d.data||{});setSelectedId(id=>id&&(d.data?.items||[]).some(x=>x.id===id)?id:(d.data?.items?.[0]?.id||""))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function loadDetail(id){if(!id){setDetail(null);return}setError("");try{const r=await fetch(`${BASE}/api/trace/v1/admin/projects/${encodeURIComponent(projectId)}/incidents/${encodeURIComponent(id)}`,{headers:headers()});const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||`HTTP ${r.status}`);setDetail(d.data)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[projectId,stage,sort]);
 useEffect(()=>{setShowHistory(false);loadDetail(selectedId)},[selectedId]);
 const items=useMemo(()=>data.items||[],[data.items]);
 const incident=detail?.incident||items.find(x=>x.id===selectedId)||null;
 return <div className="mx-auto max-w-[1560px] space-y-5">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black tracking-[-.035em] sm:text-4xl">Incidencias</h1><p className="mt-1 text-sm text-slate-500">Gestiona y da seguimiento a las excepciones del proyecto.</p></div><button onClick={()=>onReport?.()} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white">＋&nbsp;&nbsp;Reportar incidencia</button></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon="▱" label="Abiertas" value={data.metrics?.open||0}/><Metric icon="△" label="Críticas" value={data.metrics?.critical||0} tone="red"/><Metric icon="⌕" label="En corrección" value={data.metrics?.inCorrection||0} tone="amber"/><Metric icon="◌" label="Pendientes de decisión" value={data.metrics?.pendingDecision||0} tone="violet"/></section>
  <div className={`grid gap-5 ${incident?"xl:grid-cols-[minmax(0,1fr)_390px]":""}`}>
   <section className="min-w-0 space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><select value={stage} onChange={e=>setStage(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="">Todas las etapas</option>{(data.stages||[]).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option value="recent">Más recientes</option><option value="priority">Mayor prioridad</option></select></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[115px_1.4fr_1fr_110px_130px_1fr] gap-3 border-b border-slate-100 px-4 py-3 text-[10px] font-black uppercase tracking-wide text-slate-400 md:grid"><span>ID</span><span>Título</span><span>Etapa</span><span>Prioridad</span><span>Estado</span><span>Responsable</span></div>{loading?<div className="p-14 text-center text-sm text-slate-400">Cargando incidencias…</div>:<div className="divide-y divide-slate-100">{items.map(i=><button key={i.id} onClick={()=>setSelectedId(i.id)} className={`grid w-full gap-2 px-4 py-4 text-left transition hover:bg-slate-50 md:grid-cols-[115px_1.4fr_1fr_110px_130px_1fr] md:items-center md:gap-3 ${selectedId===i.id?"bg-blue-50/50 ring-1 ring-inset ring-blue-500":""}`}><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${i.blocking?"bg-red-500":"bg-blue-500"}`}/><span className="text-xs font-bold text-slate-600">{i.incident_code}</span></div><div><div className="text-sm font-black">{i.title}</div>{i.blocking&&<span className="mt-1 inline-block rounded-md bg-red-50 px-2 py-0.5 text-[9px] font-black text-red-600">Bloqueante</span>}</div><span className="text-xs text-slate-500">{i.stage_name||"Proyecto"}</span><span><Badge className={toneSeverity(i.severity)}>{severityLabel(i.severity)}</Badge></span><span><Badge className={toneStatus(i.status)}>{statusLabel(i.status)}</Badge></span><div className="flex items-center gap-2"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-600 text-[9px] font-black text-white">{initials(i.responsible_email)}</span><span className="truncate text-xs text-slate-600">{i.responsible_email||"Sin asignar"}</span></div></button>)}{!items.length&&<div className="p-14 text-center text-sm text-slate-400">No hay incidencias en este proyecto.</div>}</div>}</div><div className="text-xs text-slate-400">Mostrando {items.length} incidencia{items.length===1?"":"s"}</div></section>
   {incident&&<aside className="hidden xl:block"><IncidentDetail data={detail} incident={incident} showHistory={showHistory} setShowHistory={setShowHistory} onClose={()=>setSelectedId("")} onDecision={()=>onDecision?.(incident,()=>{load();loadDetail(incident.id)})}/></aside>}
  </div>
  {incident&&<div className="fixed inset-0 z-[85] bg-slate-950/30 xl:hidden" onMouseDown={e=>e.target===e.currentTarget&&setSelectedId("")}><div className="absolute inset-y-0 right-0 w-full max-w-[520px] overflow-y-auto bg-[#f6f8fb] p-3 shadow-2xl sm:p-5"><IncidentDetail data={detail} incident={incident} showHistory={showHistory} setShowHistory={setShowHistory} onClose={()=>setSelectedId("")} onDecision={()=>onDecision?.(incident,()=>{load();loadDetail(incident.id)})}/></div></div>}
 </div>
}
function IncidentDetail({data,incident,showHistory,setShowHistory,onClose,onDecision}){const canDecide=Boolean(incident.pending_approval_id)&&["owner","manager","supervisor"].includes(data?.viewer?.projectRole||"");return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:sticky xl:top-5"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold text-slate-500">{incident.incident_code}</div><h2 className="mt-2 text-xl font-black leading-tight">{incident.title}</h2><div className="mt-3 flex flex-wrap gap-2"><Badge className={toneStatus(incident.status)}>{statusLabel(incident.status)}</Badge><Badge className={toneSeverity(incident.severity)}>{severityLabel(incident.severity)}</Badge>{incident.blocking&&<Badge className="bg-red-600 text-white">Bloqueante</Badge>}</div></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-200">×</button></div>
 <div className="mt-5 grid gap-3 border-y border-slate-100 py-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><Info label="Etapa" value={incident.stage_name||"Proyecto"}/><Info label="Responsable" value={incident.responsible_email||"Sin asignar"}/><Info label="Fecha límite" value={date(incident.due_at)}/><Info label="Actividad afectada" value={incident.activity_title||"Sin actividad específica"}/></div>
 <Block title="Descripción"><p className="text-xs leading-5 text-slate-600">{incident.description||"Sin descripción registrada."}</p></Block>
 <Block title="Evidencias"><div className="flex gap-2">{(incident.evidenceUrls||[]).slice(0,3).map((u,i)=><a key={u+i} href={u} target="_blank" rel="noreferrer"><img src={u} alt="Evidencia" className="h-20 w-20 rounded-xl border border-slate-200 object-cover"/></a>)}{!incident.evidenceUrls?.length&&<span className="text-xs text-slate-400">No hay evidencias vinculadas directamente a esta incidencia.</span>}</div></Block>
 {incident.correction_id&&<Block title="Corrección actual"><div className="rounded-xl border border-amber-100 bg-amber-50 p-4"><div className="text-xs font-black text-amber-900">Ciclo de corrección #{incident.correction_cycle_number}</div><p className="mt-1 text-[11px] leading-5 text-amber-900/70">{incident.correction_response_notes||incident.correction_request_notes||`Estado: ${String(incident.correction_status||"").replaceAll("_"," ")}`}</p></div></Block>}
 <Block title="Próxima acción"><div className="rounded-xl border border-blue-100 bg-blue-50 p-4"><div className="text-xs font-black text-blue-900">{incident.next_action?.title||"Dar seguimiento"}</div><p className="mt-1 text-[11px] leading-5 text-blue-900/70">{incident.next_action?.description}</p></div></Block>
 {showHistory&&<Block title="Historial">{(data?.history||[]).map(h=><div key={h.id} className="border-t border-slate-100 py-3 first:border-0"><div className="text-[10px] font-black">{h.description||h.event_type}</div><div className="mt-1 text-[9px] text-slate-400">{h.occurred_at?new Date(h.occurred_at).toLocaleString("es-DO"):""}{h.actor_email?` · ${h.actor_email}`:""}</div></div>)}{!data?.history?.length&&<div className="text-xs text-slate-400">Sin eventos asociados.</div>}</Block>}
 <div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><button onClick={()=>setShowHistory(v=>!v)} className="rounded-xl border border-blue-200 px-4 py-3 text-xs font-black text-blue-600">{showHistory?"Ocultar historial":"Ver historial"}</button>{canDecide&&<button onClick={onDecision} className="rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white">Registrar decisión</button>}</div></section>}
function Metric({icon,label,value,tone="blue"}){const t=tone==="red"?"bg-red-50 text-red-600":tone==="amber"?"bg-amber-50 text-amber-600":tone==="violet"?"bg-violet-50 text-violet-600":"bg-blue-50 text-blue-600";return <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl text-lg ${t}`}>{icon}</span><div><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div></div></div>}
function Badge({children,className=""}){return <span className={`inline-flex rounded-lg px-2.5 py-1 text-[9px] font-black ${className}`}>{children}</span>}
function Info({label,value}){return <div><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</div><div className="mt-1 text-xs font-semibold text-slate-700">{value||"—"}</div></div>}
function Block({title,children}){return <div className="border-b border-slate-100 py-5"><h3 className="mb-3 text-xs font-black">{title}</h3>{children}</div>}
