import { useMemo, useState } from "react";

const STEPS=['Qué quieres controlar','Datos de la operación','Quiénes participarán','Cómo se registrará'];
function initials(email='?'){return email.split('@')[0].split(/[._-]/).slice(0,2).map(p=>p[0]?.toUpperCase()).join('')||'?'}

export default function TraceGuidedControlWizard({open,solution,templates=[],options={users:[],departments:[]},name,setName,selectedUsers=[],selectedDepartments=[],toggleUser,toggleDepartment,publicView,setPublicView,busy,onClose,onCreate,onSelectSolution}){
 const [step,setStep]=useState(0);
 const [audience,setAudience]=useState('client');
 const suggestions=useMemo(()=>templates.slice(0,6),[templates]);
 if(!open)return null;
 const canNext=step!==1||name.trim();
 return <div className="fixed inset-0 z-[100] bg-slate-950/55 backdrop-blur-sm"><div className="absolute inset-3 overflow-hidden rounded-[26px] bg-white shadow-2xl md:inset-6"><div className="flex h-full flex-col">
  <header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Nuevo control guiado</div><p className="mt-1 text-xs text-slate-500">TRACE ya trae la estructura. Tú defines el contexto y las personas.</p></div><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 text-slate-500">×</button></header>
  <div className="border-b border-slate-100 px-5 py-3"><div className="grid grid-cols-4 gap-2">{STEPS.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className="flex items-center gap-2 text-left"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-[10px] font-black ${i===step?'bg-blue-600 text-white':i<step?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-400'}`}>{i<step?'✓':i+1}</span><span className={`hidden text-[10px] font-bold md:block ${i===step?'text-slate-900':'text-slate-400'}`}>{s}</span></button>)}</div></div>
  <div className="grid min-h-0 flex-1 lg:grid-cols-[minmax(0,1fr)_350px]"><main className="min-h-0 overflow-y-auto p-5 lg:p-7">
   {step===0&&<div><h1 className="text-3xl font-black tracking-tight">¿Qué quieres controlar?</h1><p className="mt-2 text-sm text-slate-500">Elige una solución preparada. Siempre podrás adaptarla después.</p><div className="mt-5 flex flex-wrap gap-2">{['Construcción y obras','Propiedades y entregas','Mantenimiento','Alquileres','Logística','Más sectores'].map((x,i)=><button key={x} className={`rounded-full border px-3 py-2 text-[11px] font-bold ${i===0?'border-blue-300 bg-blue-50 text-blue-700':'border-slate-200 bg-white text-slate-600'}`}>{x}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{suggestions.map((t,i)=>{const active=solution?.id===t.id;return <button key={t.id} onClick={()=>onSelectSolution(t)} className={`overflow-hidden rounded-2xl border text-left shadow-sm transition hover:-translate-y-1 hover:shadow-md ${active?'border-blue-500 ring-2 ring-blue-100':'border-slate-200'}`}><div className={`grid aspect-[2.1/1] place-items-center bg-gradient-to-br ${['from-blue-50 to-cyan-100','from-indigo-50 to-slate-100','from-amber-50 to-blue-50'][i%3]}`}><span className="text-4xl">{['🏗️','🧰','🏢','🛠️','🏠','🚚'][i%6]}</span></div><div className="p-4"><div className="flex items-center justify-between"><span className="text-[9px] font-bold uppercase text-slate-400">{t.industry}</span>{active&&<span className="grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-[9px] font-black text-white">✓</span>}</div><h3 className="mt-2 text-sm font-black">{t.name}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{t.description}</p><div className="mt-3 flex gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-500">{t.stages?.length||0} pasos</span><span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-700">Vista pública</span></div></div></button>})}</div></div>}

   {step===1&&<div className="max-w-3xl"><h1 className="text-3xl font-black tracking-tight">Datos de la operación</h1><p className="mt-2 text-sm text-slate-500">Ponle contexto a la solución que TRACE ya preparó.</p><div className="mt-7 grid gap-5 md:grid-cols-2"><label className="md:col-span-2"><span className="text-xs font-black">Nombre del control o proyecto</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-50" placeholder="Ej. Residencial Vista Real · Avance de obra"/></label><label><span className="text-xs font-black">Ubicación o referencia</span><input className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Santo Domingo, RD"/></label><label><span className="text-xs font-black">Tipo de seguimiento</span><select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option>{solution?.name||'Control operacional'}</option></select></label></div></div>}

   {step===2&&<div><h1 className="text-3xl font-black tracking-tight">¿Quiénes participarán?</h1><p className="mt-2 text-sm text-slate-500">Selecciona personas y equipos. Luego podrás arrastrarlos sobre etapas y actividades.</p><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_260px]"><div className="space-y-3">{(options.users||[]).map((u,i)=><button key={u.id} onClick={()=>toggleUser(u.id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${selectedUsers.includes(u.id)?'border-blue-400 bg-blue-50':'border-slate-200 bg-white'}`}><span className="grid h-10 w-10 place-items-center rounded-full bg-slate-900 text-[10px] font-black text-white">{initials(u.email)}</span><div className="min-w-0 flex-1"><div className="truncate text-xs font-black">{u.email.split('@')[0]}</div><div className="truncate text-[10px] text-slate-400">{u.email}</div></div><select onClick={e=>e.stopPropagation()} className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-[10px]"><option>{i===0?'Administrador':'Responsable'}</option><option>Supervisor</option><option>Colaborador</option><option>Cliente / usuario</option></select><span className={`grid h-6 w-6 place-items-center rounded-full border ${selectedUsers.includes(u.id)?'border-blue-600 bg-blue-600 text-white':'border-slate-300 text-transparent'}`}>✓</span></button>)}</div><div className="rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="text-xs font-black text-blue-900">Equipos / departamentos</div><div className="mt-3 space-y-2">{(options.departments||[]).map(d=><button key={d.id} onClick={()=>toggleDepartment(d.id)} className={`w-full rounded-xl border p-3 text-left text-[10px] font-bold ${selectedDepartments.includes(d.id)?'border-blue-400 bg-white text-blue-700':'border-blue-100 bg-blue-50 text-slate-600'}`}>{d.name}</button>)}</div><div className="mt-4 border-t border-blue-100 pt-4 text-[10px] leading-5 text-blue-700">Cada persona verá solo lo que necesita según su rol y asignación.</div></div></div></div>}

   {step===3&&<div><h1 className="text-3xl font-black tracking-tight">Cómo se registrará</h1><p className="mt-2 text-sm text-slate-500">Revisa lo que TRACE cargará y decide cómo compartir el seguimiento.</p><div className="mt-6 grid gap-6 xl:grid-cols-[1fr_320px]"><div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-xs font-black">Etapas del control</div><div className="mt-3 space-y-2">{(solution?.stages||[]).map((s,i)=><div key={s.key||i} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="text-slate-300">⠿</span><span className="grid h-7 w-7 place-items-center rounded-full bg-white text-[9px] font-black text-blue-700 shadow-sm">{i+1}</span><span className="flex-1 text-[11px] font-bold text-slate-700">{s.name}</span><span className="text-emerald-600">✓</span></div>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{['Fotos y evidencias','Incidencias y correcciones','Fechas límite','Aprobaciones','Listas de verificación','Historial y bitácora'].map(x=><div key={x} className="rounded-xl border border-slate-200 bg-white p-3 text-[11px] font-bold text-slate-700">✓ {x}</div>)}</div></div><div><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="text-xs font-black">Vista pública</div><p className="mt-1 text-[10px] leading-4 text-slate-500">Elige quién podrá consultar avances autorizados.</p><div className="mt-3 space-y-2">{[['client','Cliente / inversionista'],['owner','Usuario / propietario'],['custom','Personalizada']].map(([k,l])=><button key={k} onClick={()=>{setAudience(k);setPublicView(true)}} className={`w-full rounded-xl border p-3 text-left ${audience===k?'border-blue-400 bg-blue-50':'border-slate-200'}`}><div className="text-[10px] font-black">{l}</div><div className="mt-1 text-[9px] text-slate-400">Avances, evidencias y estados autorizados.</div></button>)}</div><div className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="grid h-16 w-16 place-items-center border-4 border-slate-900 bg-white text-[9px] font-black">QR</div><div><div className="text-[10px] font-black">Acceso por enlace o QR</div><div className="mt-1 text-[9px] text-slate-400">Se genera al activar el seguimiento.</div></div></div></div></div></div></div>}
  </main>
  <aside className="hidden border-l border-slate-200 bg-[#f7f9fc] p-5 lg:block"><div className="sticky top-0"><div className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Vista previa de estructura</div><div className="mt-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="text-xs font-black">{solution?.name||'Selecciona una solución'}</div><p className="mt-1 text-[10px] leading-4 text-slate-500">Así se organizará tu control.</p><div className="mt-4 space-y-2">{['Etapas y subetapas','Responsables y equipos','Evidencias y listas','Incidencias y correcciones','Vista pública para clientes'].map(x=><div key={x} className="flex items-center gap-2 text-[10px] font-semibold text-slate-600"><span className="grid h-6 w-6 place-items-center rounded-lg bg-blue-50 text-blue-700">✓</span>{x}</div>)}</div></div><div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="text-xs font-black text-blue-900">Con TRACE inicias más rápido</div><p className="mt-2 text-[10px] leading-5 text-blue-700">La solución ya trae los controles principales. Solo asignas personas y ajustas lo necesario.</p></div></div></aside></div>
  <footer className="flex items-center justify-between border-t border-slate-200 bg-white px-5 py-3"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold disabled:opacity-30">Volver</button><div className="flex items-center gap-3"><span className="text-[10px] text-slate-400">Paso {step+1} de 4</span>{step<3?<button disabled={!canNext||(!solution&&step===0)} onClick={()=>setStep(step+1)} className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">Continuar</button>:<button disabled={busy||!solution||!name.trim()} onClick={onCreate} className="rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-black text-white disabled:opacity-40">{busy?'Activando…':'Activar TRACE'}</button>}</div></footer>
 </div></div></div>
}
