import{useEffect,useState}from'react';
import{useParams}from'react-router-dom';

const BASE=import.meta.env.VITE_API_URL||'https://api.code.intaprd.com';
const ROLE={owner:'Propietario',manager:'Responsable',supervisor:'Supervisor',member:'Miembro',observer:'Observador'};

export default function TraceTeamInvitationPage(){
 const{token}=useParams();const[data,setData]=useState(null),[phone,setPhone]=useState(''),[code,setCode]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(null);
 useEffect(()=>{let live=true;(async()=>{setLoading(true);setError('');try{const r=await fetch(`${BASE}/api/trace/v1/public/team-invitations/${encodeURIComponent(token||'')}`);const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||'Invitación no disponible');if(live)setData(d.data)}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[token]);
 async function accept(){setBusy(true);setError('');try{const r=await fetch(`${BASE}/api/trace/v1/public/team-invitations/${encodeURIComponent(token||'')}/accept`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,phone:data?.requiresPhone?phone:undefined})});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d.message||d.error||'No se pudo aceptar la invitación');setDone(d.data)}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(loading)return <Shell><div className="text-center text-sm text-slate-500">Verificando invitación…</div></Shell>;
 if(done)return <Shell><div className="text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-2xl">✓</div><h1 className="mt-5 text-2xl font-black text-slate-950">Invitación aceptada</h1><p className="mt-2 text-sm text-slate-500">Ya formas parte de <b>{done.projectName}</b> como {ROLE[done.projectRole]||done.projectRole}.</p><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-left text-xs leading-5 text-slate-600">Tu identidad quedó vinculada al proyecto. Para el acceso operativo puedes autenticarte mediante {done.access?.method==='phone_otp'?'tu teléfono':'tu correo'} usando un código temporal.</div><button onClick={()=>window.location.assign('/trace-operational')} className="mt-6 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">Ir al acceso operativo</button></div></Shell>;
 return <Shell><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-blue-600">KAWVO TRACE · INVITACIÓN</div><h1 className="mt-2 text-2xl font-black text-slate-950">Únete al proyecto</h1>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</div>}{data&&<><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="text-sm font-black text-slate-900">{data.projectName}</div><div className="mt-1 text-xs text-slate-500">Rol: {ROLE[data.role]||data.role}</div><div className="mt-3 text-[11px] text-slate-400">Invitación para {data.emailHint}{data.phoneHint?` · ${data.phoneHint}`:''}</div></div>{data.requiresPhone&&<><label className="mt-5 block text-xs font-black text-slate-700">Tu número de teléfono</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+18095550000" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"/></>}<label className="mt-4 block text-xs font-black text-slate-700">Código de invitación</label><input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-center text-xl font-black tracking-[.35em]"/><p className="mt-3 text-[11px] leading-5 text-slate-400">Este enlace y su código son de un solo uso. Si recibiste la invitación por WhatsApp, verifica también el número asociado.</p><button disabled={busy||code.length!==6||(data.requiresPhone&&!phone)} onClick={accept} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{busy?'Verificando…':'Verificar y aceptar'}</button></>}</div></Shell>}

function Shell({children}){return <div className="min-h-screen bg-slate-100 px-4 py-10"><div className="mx-auto w-full max-w-md rounded-3xl border border-slate-200 bg-white p-6 shadow-xl"><div className="mb-7 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 font-black text-white">K</div><div><div className="font-black text-slate-950">KAWVO Trace</div><div className="text-[10px] text-slate-400">Tecnología para avanzar</div></div></div>{children}</div></div>}
