import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";

const BASE = import.meta.env.VITE_API_URL || "https://api.code.intaprd.com";
function human(v){return ({pending:"Pendiente",assigned:"Asignado",in_progress:"En curso",paused:"Pausado",blocked:"Bloqueado",pending_approval:"Por confirmar",correction_required:"En corrección",completed:"Completado",approved:"Aprobado",cancelled:"Cancelado",overdue:"Atrasado"}[v]||String(v||"Pendiente").replaceAll("_"," "));}
function clamp(v){return Math.max(0,Math.min(100,Number(v||0)))}

export default function TracePublicPage(){
  const {slug}=useParams();
  const [data,setData]=useState(null);
  const [error,setError]=useState("");
  useEffect(()=>{(async()=>{try{const r=await fetch(`${BASE}/api/trace/v1/public/${encodeURIComponent(slug)}`);const d=await r.json();if(!r.ok||d?.ok===false)throw new Error("Este seguimiento no está disponible.");setData(d.data);}catch(e){setError(e.message);}})();},[slug]);
  const milestones=useMemo(()=>data?.milestones||data?.stages||[],[data]);
  const evidence=useMemo(()=>data?.evidences||data?.evidence||[],[data]);
  if(error)return <div className="grid min-h-screen place-items-center bg-slate-50 p-6"><div className="max-w-md text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-900 text-white">T</div><h1 className="mt-5 text-xl font-black text-slate-900">Seguimiento no disponible</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></div>;
  if(!data)return <div className="grid min-h-screen place-items-center bg-slate-50 text-sm text-slate-500">Cargando seguimiento…</div>;
  const progress=clamp(data.progress);
  return <div className="min-h-screen bg-[#f5f7fb] text-slate-900">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 font-black text-white">T</div><div><div className="font-black tracking-tight">TRACE</div><div className="text-[10px] text-slate-400">Seguimiento compartido</div></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold text-slate-600 sm:block">Referencia: {data.reference}</span><button onClick={()=>navigator.share?.({title:data.title,url:location.href})} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700">Compartir</button></div></div></header>

    <main className="mx-auto max-w-6xl space-y-5 p-5 sm:p-8">
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-2xl"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-blue-700">Seguimiento público</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold text-emerald-700">Información autorizada</span></div><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">{data.title}</h1><p className="mt-2 text-sm text-slate-500">{data.control}</p>{data.item&&<div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-xl bg-slate-50 px-3 py-2 font-semibold text-slate-700">{data.item}</span>{data.itemCode&&<span className="rounded-xl bg-slate-50 px-3 py-2 text-slate-500">{data.itemCode}</span>}</div>}</div><div className="flex min-w-[260px] items-center gap-5"><div className="grid h-32 w-32 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#2563eb 0 ${progress}%,#e2e8f0 ${progress}% 100%)`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><div><div className="text-2xl font-black">{progress}%</div><div className="text-[9px] text-slate-400">avance</div></div></div></div><div><div className="text-xs font-semibold text-slate-500">Estado actual</div><div className="mt-1 text-lg font-black">{human(data.status)}</div><div className="mt-3 h-2 w-28 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${progress}%`}}/></div></div></div></div></section>

      <section className="grid gap-5 lg:grid-cols-[.95fr_1.35fr]">
        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Hitos del seguimiento</h2><p className="mt-1 text-[11px] text-slate-500">Etapas visibles para cliente, propietario o inversionista.</p></div><span className="text-xs font-bold text-blue-600">{milestones.length||'—'}</span></div><div className="mt-5 space-y-1">{milestones.length?milestones.map((m,i)=><div key={m.id||m.name||i} className="relative flex gap-3 pb-5 last:pb-0"><div className="relative flex w-7 justify-center"><span className={`relative z-10 grid h-7 w-7 place-items-center rounded-full text-[9px] font-black ${['completed','approved'].includes(m.status)?'bg-emerald-500 text-white':m.status==='in_progress'?'bg-blue-600 text-white':'bg-slate-100 text-slate-400'}`}>{['completed','approved'].includes(m.status)?'✓':i+1}</span>{i<milestones.length-1&&<span className="absolute bottom-0 top-7 w-px bg-slate-200"/>}</div><div><div className="text-xs font-black text-slate-800">{m.name||m.title||`Etapa ${i+1}`}</div><div className="mt-1 text-[10px] text-slate-400">{human(m.status)}</div></div></div>):<div className="rounded-2xl bg-slate-50 p-5 text-xs leading-5 text-slate-500">El seguimiento está activo. Los hitos autorizados aparecerán aquí cuando estén disponibles en la vista compartida.</div>}</div></div>

        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Evidencia reciente</h2><p className="mt-1 text-[11px] text-slate-500">Fotos y registros autorizados que respaldan el avance.</p></div><span className="text-xs font-bold text-blue-600">{evidence.length?`${evidence.length} visibles`:'Seguimiento seguro'}</span></div>{evidence.length?<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{evidence.slice(0,8).map((ev,i)=><div key={ev.id||i} className="overflow-hidden rounded-2xl border border-slate-200 bg-slate-50"><div className="grid aspect-[4/3] place-items-center bg-gradient-to-br from-blue-50 to-slate-200 text-2xl">▧</div><div className="p-2"><div className="truncate text-[10px] font-bold">{ev.caption||ev.original_filename||'Evidencia'}</div><div className="mt-1 text-[9px] text-slate-400">{ev.created_at||'Registro autorizado'}</div></div></div>)}</div>:<div className="mt-5 grid min-h-[220px] place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50 text-center"><div className="max-w-xs"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-xl text-blue-600">▧</div><div className="mt-3 text-xs font-black">Evidencias bajo control</div><p className="mt-1 text-[10px] leading-5 text-slate-400">Solo se muestran imágenes y documentos expresamente autorizados para esta vista.</p></div></div>}</div>
      </section>

      <section className="rounded-3xl border border-blue-100 bg-blue-50 p-5 sm:flex sm:items-center sm:justify-between"><div><div className="text-xs font-black text-blue-900">Seguimiento transparente, información protegida</div><p className="mt-1 max-w-3xl text-[11px] leading-5 text-blue-700">TRACE comparte el progreso y las evidencias autorizadas sin exponer notas internas, conversaciones privadas, configuraciones ni datos del equipo.</p></div><div className="mt-4 rounded-xl bg-white px-4 py-2 text-[10px] font-bold text-blue-700 shadow-sm sm:mt-0">Actualización segura</div></section>
    </main>
  </div>;
}
