import { useEffect, useMemo, useState } from "react";
import TraceStandaloneShell from "../components/trace/TraceStandaloneShell.jsx";
import TraceDashboardHome from "../components/trace/TraceDashboardHome.jsx";
import TraceSolutionsLibrary from "../components/trace/TraceSolutionsLibrary.jsx";
import TraceOperationBoard from "../components/trace/TraceOperationBoard.jsx";
import TraceGuidedControlWizard from "../components/trace/TraceGuidedControlWizard.jsx";
import TraceActivityModal from "../components/trace/TraceActivityModal.jsx";
import TraceTeamDirectory from "../components/trace/TraceTeamDirectory.jsx";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
const API="/api/trace/v1/admin";
const CC=`${API}/command-center`;
function auth(extra={}){const token=localStorage.getItem("qr_token")||"";return{...(token?{Authorization:`Bearer ${token}`}:{}) ,...extra}}
async function req(path,options={}){const r=await fetch(`${BASE}${path}`,{...options,headers:auth({"Content-Type":"application/json",...(options.headers||{})})});const d=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok||d?.ok===false)throw new Error(d?.message||d?.error||`HTTP ${r.status}`);return d}
function SimplePage({title,subtitle,children}){return <div className="mx-auto max-w-[1560px] space-y-5"><div><div className="text-xs font-black uppercase tracking-[.16em] text-blue-600">TRACE</div><h1 className="mt-1 text-3xl font-black tracking-tight">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{children}</div>}

export default function TraceCommandCenterPage(){
 const [view,setView]=useState("home");
 const [overview,setOverview]=useState({metrics:{},executions:[],incidents:[],approvals:[]});
 const [templates,setTemplates]=useState([]),[options,setOptions]=useState({users:[],departments:[]});
 const [workspace,setWorkspace]=useState(null),[selectedExecution,setSelectedExecution]=useState("");
 const [selectedSolution,setSelectedSolution]=useState(null),[wizardOpen,setWizardOpen]=useState(false);
 const [controlName,setControlName]=useState(""),[selectedUsers,setSelectedUsers]=useState([]),[selectedDepartments,setSelectedDepartments]=useState([]),[publicView,setPublicView]=useState(true);
 const [activityOpen,setActivityOpen]=useState(false),[activityText,setActivityText]=useState(""),[activityType,setActivityType]=useState("progress.updated");
 const [selectedIncident,setSelectedIncident]=useState(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const[o,t,s]=await Promise.all([req(`${API}/overview`),req(`${API}/templates`),req(`${API}/setup-options`)]);setOverview(o.data||{});setTemplates(t.data||[]);setOptions(s.data||{users:[],departments:[]});setSelectedSolution(v=>v||t.data?.[0]||null)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function openExecution(id){if(!id)return;setSelectedExecution(id);setError("");try{const d=await req(`${CC}/executions/${encodeURIComponent(id)}`);setWorkspace(d.data);setView("operations")}catch(e){setError(e.message)}}
 async function assign(stageId,userId){if(!stageId||!userId)return;setBusy(true);try{await req(`${CC}/stages/${encodeURIComponent(stageId)}/assign`,{method:"POST",body:JSON.stringify({userId})});await openExecution(selectedExecution);setMessage("Responsable asignado.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveActivity(){if(!selectedExecution||!activityText.trim())return setError("Selecciona una operación y describe lo ocurrido.");setBusy(true);try{await req(`${API}/activities`,{method:"POST",body:JSON.stringify({executionId:selectedExecution,type:activityType,description:activityText.trim()})});setActivityOpen(false);setActivityText("");await load();if(selectedExecution)await openExecution(selectedExecution);setMessage("Actividad registrada en la bitácora.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function createControl(){if(!selectedSolution||!controlName.trim())return;setBusy(true);try{const d=await req(`${API}/controls`,{method:"POST",body:JSON.stringify({templateId:selectedSolution.id,name:controlName.trim(),responsibleUserIds:selectedUsers,departmentIds:selectedDepartments,publicView})});setWizardOpen(false);setMessage(`Control activado: ${d.data.name}.`);await load();setView("home")}catch(e){setError(e.message)}finally{setBusy(false)}}
 function toggle(list,setter,id){setter(list.includes(id)?list.filter(x=>x!==id):[...list,id])}
 function startSolution(sol=selectedSolution){if(sol){setSelectedSolution(sol);setControlName(sol.name);setSelectedUsers([]);setSelectedDepartments([]);setPublicView(true)}setWizardOpen(true)}
 const work=overview.executions||[],incidents=overview.incidents||[],approvals=overview.approvals||[],metrics=overview.metrics||{};
 const evaluationTemplates=useMemo(()=>templates.filter(t=>['quality','service','hospitality'].includes(t.industry)),[templates]);

 return <TraceStandaloneShell view={view} onView={setView} onNewControl={()=>startSolution()} onRegister={()=>{setSelectedExecution(selectedExecution||work[0]?.id||"");setActivityOpen(true)}}>
  {loading&&<div className="fixed inset-x-0 top-[70px] z-20 h-0.5 overflow-hidden bg-blue-50"><div className="h-full w-1/3 animate-pulse bg-blue-600"/></div>}
  {error&&<div className="mx-auto mb-4 max-w-[1560px] rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</div>}
  {message&&<div className="mx-auto mb-4 flex max-w-[1560px] items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
  {view==="home"&&<TraceDashboardHome metrics={metrics} work={work} incidents={incidents} onOpenOperation={openExecution} onSupervision={()=>setView("supervision")} onSolutions={()=>setView("solutions")}/>}
  {view==="solutions"&&<TraceSolutionsLibrary templates={templates} selected={selectedSolution} onSelect={setSelectedSolution} onUse={startSolution}/>}
  {view==="operations"&&<TraceOperationBoard workspace={workspace} onAssign={assign} onOpenIncident={setSelectedIncident} onRegister={()=>setActivityOpen(true)}/>}
  {view==="supervision"&&<SimplePage title="Supervisión y decisiones" subtitle="Incidencias, correcciones y confirmaciones que requieren atención."><div className="grid gap-4 xl:grid-cols-[1.3fr_.8fr]"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><h2 className="font-black">Incidencias y correcciones</h2><div className="flex gap-2"><button className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold">Estado⌄</button><button className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[10px] font-bold">Prioridad⌄</button></div></div><div className="divide-y divide-slate-100">{incidents.map((i,idx)=><button key={i.id} onClick={()=>setSelectedIncident(i)} className="grid w-full gap-3 p-4 text-left hover:bg-slate-50 md:grid-cols-[1fr_.35fr_.35fr_auto] md:items-center"><div><div className="text-xs font-black">{i.title}</div><div className="mt-1 text-[10px] text-slate-400">{i.execution_title||i.execution_code}</div></div><span className="text-[10px] text-slate-500">{i.severity||'media'}</span><span className="text-[10px] font-bold text-blue-600">{i.status||'abierta'}</span><span className="text-lg text-slate-300">›</span></button>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black">Pendientes de confirmar</h2><div className="mt-4 space-y-2">{approvals.map(a=><div key={a.id} className="rounded-xl border border-slate-200 p-3"><div className="text-[11px] font-black">{a.execution_title||a.execution_code}</div><div className="mt-1 text-[10px] text-slate-400">{a.stage_name||'Revisión pendiente'}</div><button className="mt-3 w-full rounded-lg bg-blue-600 px-3 py-2 text-[10px] font-black text-white">Abrir revisión</button></div>)}{!approvals.length&&<div className="rounded-xl bg-emerald-50 p-4 text-xs font-semibold text-emerald-700">No hay aprobaciones pendientes.</div>}</div></div></div></SimplePage>}
  {view==="evaluations"&&<SimplePage title="Evaluaciones y formularios" subtitle="Listas de verificación, calificaciones y encuestas conectadas a la operación."><div className="grid gap-4 md:grid-cols-3">{[['✓','Listas de verificación','Controla puntos y convierte hallazgos en acciones.'],['★','Calificaciones','Mide calidad de trabajos, entregas y servicios.'],['◌','Encuestas','Recoge satisfacción y nivel de recomendación.']].map(x=><button key={x[1]} onClick={()=>setView('solutions')} className="rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-xl font-black text-blue-600">{x[0]}</span><h3 className="mt-4 text-lg font-black">{x[1]}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{x[2]}</p><div className="mt-5 text-[10px] font-bold text-blue-600">{evaluationTemplates.length?`${evaluationTemplates.length} soluciones disponibles`:'Crear desde una solución'} →</div></button>)}</div></SimplePage>}
  {view==="reports"&&<SimplePage title="Reportes y resultados" subtitle="Lectura visual de avance, incidencias, cumplimiento y calidad."><TraceDashboardHome metrics={metrics} work={work} incidents={incidents} onOpenOperation={openExecution} onSupervision={()=>setView('supervision')} onSolutions={()=>setView('solutions')}/></SimplePage>}
  {view==="team"&&<SimplePage title="Equipos y responsables" subtitle="Personas, departamentos y responsabilidades disponibles para asignar."><TraceTeamDirectory users={options.users||[]} departments={options.departments||[]}/></SimplePage>}
  {view==="settings"&&<SimplePage title="Configuración" subtitle="Ajustes del espacio TRACE, permisos, reglas y vistas compartidas."><div className="grid gap-4 md:grid-cols-3">{['Roles y permisos','Reglas y notificaciones','Vista pública'].map(x=><div key={x} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm font-black">{x}</div><p className="mt-2 text-xs text-slate-500">Configura esta parte sin modificar la estructura base de tus controles.</p></div>)}</div></SimplePage>}
  <TraceGuidedControlWizard open={wizardOpen} solution={selectedSolution} templates={templates} options={options} name={controlName} setName={setControlName} selectedUsers={selectedUsers} selectedDepartments={selectedDepartments} toggleUser={id=>toggle(selectedUsers,setSelectedUsers,id)} toggleDepartment={id=>toggle(selectedDepartments,setSelectedDepartments,id)} publicView={publicView} setPublicView={setPublicView} busy={busy} onClose={()=>setWizardOpen(false)} onCreate={createControl} onSelectSolution={setSelectedSolution}/>
  <TraceActivityModal open={activityOpen} work={work} executionId={selectedExecution} setExecutionId={setSelectedExecution} type={activityType} setType={setActivityType} description={activityText} setDescription={setActivityText} busy={busy} onClose={()=>setActivityOpen(false)} onSave={saveActivity}/>
  {selectedIncident&&<div className="fixed inset-0 z-[90] bg-slate-950/25" onClick={()=>setSelectedIncident(null)}><aside className="absolute inset-y-0 right-0 w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-red-600">Incidencia</div><h2 className="mt-1 text-xl font-black">{selectedIncident.title}</h2></div><button onClick={()=>setSelectedIncident(null)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200">×</button></div><p className="mt-3 text-xs leading-5 text-slate-500">{selectedIncident.description||'Incidencia vinculada al seguimiento y a su contexto operacional.'}</p><div className="mt-6 grid grid-cols-2 gap-3">{[['Estado',selectedIncident.status||'Abierta'],['Prioridad',selectedIncident.severity||'Media'],['Operación',selectedIncident.execution_title||selectedIncident.execution_code||'TRACE'],['Próxima acción','Corregir y validar']].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3"><div className="text-[9px] font-bold uppercase text-slate-400">{l}</div><div className="mt-1 text-[11px] font-black text-slate-700">{v}</div></div>)}</div><div className="mt-6 border-t border-slate-100 pt-5"><div className="flex gap-4 border-b border-slate-100 text-xs font-bold"><button className="border-b-2 border-blue-600 pb-3 text-blue-700">Detalles</button><button className="pb-3 text-slate-400">Comentarios</button><button className="pb-3 text-slate-400">Evidencias</button></div><div className="mt-5 space-y-3">{['Incidencia reportada','Asignada a responsable','Corrección en seguimiento'].map((x,i)=><div key={x} className="flex gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-50 text-[9px] font-black text-blue-700">{i+1}</span><div><div className="text-[11px] font-black">{x}</div><div className="text-[9px] text-slate-400">Registrado en la bitácora TRACE</div></div></div>)}</div></div><button className="mt-8 w-full rounded-xl bg-blue-600 px-4 py-3 text-xs font-black text-white">Marcar como resuelta</button></aside></div>}
 </TraceStandaloneShell>
}
