import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
export default function TraceProjectPublicPage(){
 const{slug}=useParams();const[data,setData]=useState(null),[error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch(`${BASE}/api/trace/v1/public/projects/${encodeURIComponent(slug)}`);const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"No encontramos este proyecto.");if(live)setData(d.data)}catch(e){if(live)setError(e.message)}})();return()=>{live=false}},[slug]);
 if(error)return <div className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className="max-w-md text-center"><div className="text-4xl">⌁</div><h1 className="mt-4 text-2xl font-black">Enlace no disponible</h1><p className="mt-2 text-sm text-slate-500">{error}</p></div></div>;
 if(!data)return <div className="min-h-screen grid place-items-center bg-slate-50 text-sm text-slate-400">Cargando seguimiento…</div>;
 return <div className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-3xl px-5 py-8 sm:px-8"><header className="flex items-baseline gap-2"><b className="text-xl">KAWVO</b><span className="text-xl font-semibold text-blue-600">Trace</span></header><main className="mt-10"><span className="inline-flex rounded-full bg-green-50 px-3 py-1 text-xs font-black text-green-700">Seguimiento activo</span><h1 className="mt-4 text-4xl font-black tracking-tight">{data.name}</h1>{data.location&&<p className="mt-2 text-sm text-slate-500">{data.location}</p>}<div className="mt-7 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Seguimiento</p><h2 className="mt-2 text-xl font-black">{data.tracking||"Trace"}</h2>{data.description&&<p className="mt-2 text-sm leading-6 text-slate-500">{data.description}</p>}</div><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-black">Etapas</h2><div className="mt-4 space-y-3">{data.stages?.map((s,i)=><div key={`${s.order}-${s.name}`} className="flex items-center gap-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-50 text-xs font-black text-blue-700">{i+1}</span><div className="h-px flex-1 bg-slate-100 sm:hidden"/><span className="flex-1 text-sm font-semibold">{s.name}</span></div>)}</div></section><p className="mt-6 text-xs leading-5 text-slate-400">Esta vista muestra únicamente información autorizada del proyecto. Datos internos, responsables, incidencias privadas y conversaciones no se publican aquí.</p></main></div></div>
}
