import { useEffect, useMemo, useState } from "react";
import TraceControlWizard from "../components/trace/TraceControlWizard.jsx";
import TraceActivityModal from "../components/trace/TraceActivityModal.jsx";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
const API="/api/trace/v1/admin";
const SECTORS={construction:["Construcción","Construcción y propiedades"],property:["Propiedades","Construcción y propiedades"],rental:["Alquileres","Construcción y propiedades"],maintenance:["Mantenimiento","Construcción y propiedades"],logistics:["Logística","Logística y almacenes"],warehouse:["Almacenes","Logística y almacenes"],hospitality:["Hotelería","Hotelería y servicios"],service:["Evaluación y servicio","Evaluaciones y calidad"],general:["Otros","Otros sectores"]};
const GROUPS=["Construcción y propiedades","Logística y almacenes","Hotelería y servicios","Evaluaciones y calidad","Otros sectores"];

function auth(extra={}){const t=localStorage.getItem("qr_token")||"";return{...(t?{Authorization:`Bearer ${t}`}:{}) ,...extra};}
async function req(path,options={}){const r=await fetch(`${BASE}${path}`,{...options,headers:auth({"Content-Type":"application/json",...(options.headers||{})})});const d=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok||d?.ok===false)throw new Error(d?.message||d?.error||`HTTP ${r.status}`);return d;}
function status(v){return({pending:"Pendiente",assigned:"Asignado",in_progress:"En curso",paused:"Pausado",blocked:"Bloqueado",pending_approval:"Por confirmar",correction_required:"Requiere corrección",completed:"Completado",cancelled:"Cancelado",overdue:"Atrasado",draft:"Por terminar",active:"Activo",open:"Abierta",approved:"Aprobado",rejected:"Rechazado"}[v]||String(v||"Pendiente").replaceAll("_"," "));}
function Badge({value}){const tone=["completed","active","approved"].includes(value)?"bg-emerald-50 text-emerald-700":["blocked","overdue","rejected"].includes(value)?"bg-red-50 text-red-700":["pending_approval","correction_required","open"].includes(value)?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${tone}`}>{status(value)}</span>;}

export default function TraceWorkspaceV2Page(){
 const [view,setView]=useState("home"),[overview,setOverview]=useState({metrics:{},processes:[],executions:[],incidents:[],approvals:[]}),[templates,setTemplates]=useState([]),[options,setOptions]=useState({users:[],departments:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [solution,setSolution]=useState(null),[controlName,setControlName]=useState(""),[selectedUsers,setSelectedUsers]=useState([]),[selectedDepartments,setSelectedDepartments]=useState([]),[publicView,setPublicView]=useState(true),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false);
 const [activityOpen,setActivityOpen]=useState(false),[executionId,setExecutionId]=useState(""),[activityType,setActivityType]=useState("progress.updated"),[activityText,setActivityText]=useState(""),[shareResult,setShareResult]=useState(null);
 async function load(){setLoading(true);setError("");try{const[o,t,s]=await Promise.all([req(`${API}/overview`),req(`${API}/templates`),req(`${API}/setup-options`)]);setOverview(o.data||{});setTemplates(t.data||[]);setOptions(s.data||{users:[],departments:[]});}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const groups=useMemo(()=>{const b={};templates.forEach(t=>{if(filter!=="all"&&t.industry!==filter)return;const g=(SECTORS[t.industry]||SECTORS.general)[1];(b[g]||(b[g]=[])).push(t);});return b;},[templates,filter]);
 const m=overview.metrics||{},controls=overview.processes||[],work=overview.executions||[],incidents=overview.incidents||[],approvals=overview.approvals||[];
 function choose(t){setSolution(t);setControlName(t.name);setSelectedUsers([]);setSelectedDepartments([]);setPublicView(true);setError("");}
 function toggle(list,setter,id){setter(list.includes(id)?list.filter(x=>x!==id):[...list,id]);}
 async function create(){if(!controlName.trim())return setError("Escribe dónde usarás este control.");setBusy(true);setError("");try{const d=await req(`${API}/controls`,{method:"POST",body:JSON.stringify({templateId:solution.id,name:controlName.trim(),responsibleUserIds:selectedUsers,departmentIds:selectedDepartments,publicView})});setSolution(null);setMessage(`Control listo: ${d.data.name}. TRACE dejó ${d.data.steps} pasos preparados.`);await load();setView("controls");}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function saveActivity(){if(!executionId||!activityText.trim())return setError("Selecciona un trabajo y describe lo ocurrido.");setBusy(true);setError("");try{await req(`${API}/activities`,{method:"POST",body:JSON.stringify({executionId,type:activityType,description:activityText.trim()})});setActivityOpen(false);setActivityText("");setMessage("Actividad registrada en el historial.");await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function share(id){setBusy(true);setError("");try{const d=await req(`${API}/executions/${encodeURIComponent(id)}/public-view`,{method:"POST",body:"{}"});setShareResult(d.data);}catch(e){setError(e.message);}finally{setBusy(false);}}

 return <div className="mx-auto max-w-7xl space-y-6 pb-12">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-blue-600">INTAP TRACE · V1</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Control de tu operación</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">Soluciones listas para usar. Tu equipo registra lo que ocurre y TRACE organiza avances, pendientes, evidencias e historial.</p></div><div className="flex gap-2"><button onClick={()=>setView("catalog")} className="btn-primary">+ Nuevo control</button><button onClick={()=>{setExecutionId(work[0]?.id||"");setActivityOpen(true);}} className="btn-secondary">Registrar actividad</button></div></header>
  <nav className="flex gap-1 overflow-x-auto border-b border-slate-200">{[["home","Inicio"],["controls","Controles"],["supervision","Supervisión"],["evaluations","Evaluaciones"],["results","Resultados"],["catalog","Soluciones"]].map(([k,l])=><button key={k} onClick={()=>setView(k)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${view===k?"border-blue-600 text-blue-700":"border-transparent text-slate-500"}`}>{l}</button>)}<a href="/dashboard/trace-management" className="whitespace-nowrap border-b-2 border-transparent px-4 py-3 text-sm font-semibold text-slate-500">Configuración</a></nav>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}

  {view==="home"&&<section className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Controles activos",m.activeProcesses||0],["Trabajos en curso",m.inProgress||0],["Requieren atención",(m.openIncidents||0)+(m.correctionStages||0)],["Pendientes de confirmar",m.pendingApprovals||0]].map(([l,v],i)=><button key={l} onClick={()=>setView(i<2?"controls":"supervision")} className="card p-4 text-left hover:border-blue-200"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-2xl font-bold text-slate-900">{v}</div></button>)}</div><div className="grid gap-4 lg:grid-cols-3"><div className="card p-5 lg:col-span-2"><div className="flex justify-between"><div><h2 className="font-bold text-slate-900">Qué está pasando ahora</h2><p className="text-xs text-slate-500">Actividad de los controles en uso.</p></div><button onClick={()=>setActivityOpen(true)} className="text-xs font-semibold text-blue-700">+ Registrar</button></div><div className="mt-4 space-y-3">{work.slice(0,6).map(w=><div key={w.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3"><div><div className="text-sm font-semibold text-slate-900">{w.title||w.process_name}</div><div className="text-xs text-slate-500">{w.asset_name||w.process_name}</div></div><div className="flex items-center gap-2"><span className="text-xs text-slate-500">{Number(w.completion_percentage||0)}%</span><Badge value={w.status}/></div></div>)}{!work.length&&<div className="py-8 text-center text-sm text-slate-500">Cuando un control tenga trabajo en curso, aparecerá aquí.</div>}</div></div><div className="space-y-4"><div className="card p-5"><h3 className="font-bold text-slate-900">Acciones rápidas</h3><button onClick={()=>setView("catalog")} className="mt-4 w-full rounded-xl border border-blue-200 bg-blue-50 p-3 text-left text-sm font-semibold text-blue-800">Crear un control listo</button><button onClick={()=>setActivityOpen(true)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold text-slate-800">Registrar lo ocurrido</button></div><div className="card p-5"><h3 className="font-bold text-slate-900">Vista para clientes y usuarios</h3><p className="mt-2 text-xs leading-5 text-slate-500">Comparte avances autorizados por enlace o QR, sin exponer información interna.</p></div></div></div></section>}

  {view==="catalog"&&<section className="space-y-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="text-xl font-bold text-slate-900">¿Qué quieres controlar?</h2><p className="mt-1 text-sm text-slate-500">Elige una solución. Los pasos principales ya vienen preparados.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="all">Todos los sectores</option>{Object.entries(SECTORS).filter(([k])=>k!=="general").map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></div>{loading?<div className="card p-8 text-sm text-slate-500">Cargando soluciones…</div>:GROUPS.map(g=>{const list=groups[g]||[];if(!list.length)return null;return <div key={g} className="space-y-3"><div><h3 className="font-bold text-slate-900">{g}</h3>{g==="Construcción y propiedades"&&<p className="text-xs text-blue-600">Especialidad prioritaria de INTAP TRACE</p>}</div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map(t=><button key={t.id} onClick={()=>choose(t)} className="card p-5 text-left hover:border-blue-300"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600">{(SECTORS[t.industry]||SECTORS.general)[0]}</span><h4 className="mt-3 font-bold text-slate-900">{t.name}</h4><p className="mt-2 text-sm text-slate-500">{t.description}</p><div className="mt-4 text-xs font-semibold text-slate-500">{t.stages?.length||0} pasos listos</div></button>)}</div></div>})}</section>}

  {view==="controls"&&<section className="space-y-5"><div className="flex items-end justify-between"><div><h2 className="text-xl font-bold text-slate-900">Mis controles</h2><p className="text-sm text-slate-500">Controles activos de tu empresa.</p></div><button onClick={()=>setView("catalog")} className="btn-primary">+ Nuevo control</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{controls.map(c=><article key={c.id} className="card p-5"><div className="flex justify-between gap-3"><h3 className="font-bold text-slate-900">{c.name}</h3><Badge value={c.status}/></div><p className="mt-2 text-sm text-slate-500">{c.description||"Control operativo"}</p><div className="mt-4 border-t border-slate-100 pt-4 text-xs text-slate-500"><strong className="text-slate-800">{c.execution_count||0}</strong> trabajos vinculados</div></article>)}</div>{work.length>0&&<div className="card p-5"><h3 className="font-bold text-slate-900">Compartir seguimiento</h3><p className="mt-1 text-sm text-slate-500">Genera una vista segura para cliente, propietario, inversionista o usuario.</p><div className="mt-4 space-y-2">{work.slice(0,8).map(w=><div key={w.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div><div className="text-sm font-semibold text-slate-900">{w.title||w.process_name}</div><div className="text-xs text-slate-500">{w.execution_code}</div></div><button onClick={()=>share(w.id)} className="btn-secondary">Preparar vista pública</button></div>)}</div>{shareResult&&<div className="mt-4 rounded-xl bg-emerald-50 p-4"><div className="text-sm font-bold text-emerald-900">Vista pública lista</div><a target="_blank" rel="noreferrer" href={`/trace-public/${shareResult.slug}`} className="mt-2 inline-block text-sm font-semibold text-emerald-700 underline">Abrir vista compartida ↗</a></div>}</div>}</section>}

  {view==="supervision"&&<section className="space-y-5"><div><h2 className="text-xl font-bold text-slate-900">Supervisión</h2><p className="text-sm text-slate-500">Lo que necesita revisión, corrección o confirmación.</p></div><div className="grid gap-4 lg:grid-cols-2"><div className="card p-5"><h3 className="font-bold">Incidencias y correcciones</h3><div className="mt-4 space-y-3">{incidents.slice(0,10).map(i=><div key={i.id} className="border-b pb-3"><div className="text-sm font-semibold">{i.title}</div><div className="text-xs text-slate-500">{i.execution_title||i.execution_code} · {status(i.status)}</div></div>)}</div></div><div className="card p-5"><h3 className="font-bold">Pendientes de confirmar</h3><div className="mt-4 space-y-3">{approvals.slice(0,10).map(a=><div key={a.id} className="border-b pb-3"><div className="text-sm font-semibold">{a.execution_title||a.execution_code}</div><div className="text-xs text-slate-500">{a.stage_name||"Revisión"} · {status(a.status)}</div></div>)}</div></div></div></section>}

  {view==="evaluations"&&<section className="space-y-5"><div><h2 className="text-xl font-bold text-slate-900">Evaluaciones y formularios</h2><p className="text-sm text-slate-500">Listas de verificación, encuestas y calificaciones.</p></div><div className="grid gap-4 md:grid-cols-3">{[["Listas de verificación","Comprueba puntos y registra hallazgos."],["Calificaciones","Mide calidad de trabajos y servicios."],["Encuestas","Recoge opiniones y nivel de recomendación."]].map(([a,b])=><div className="card p-5" key={a}><h3 className="font-bold">{a}</h3><p className="mt-2 text-sm text-slate-500">{b}</p></div>)}</div><button onClick={()=>{setFilter("service");setView("catalog");}} className="btn-primary">Crear desde una solución</button></section>}
  {view==="results"&&<section className="space-y-5"><div><h2 className="text-xl font-bold text-slate-900">Resultados</h2><p className="text-sm text-slate-500">Avance, cumplimiento, incidencias, calificaciones y evaluaciones.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Trabajos completados",m.completed||0],["Incidencias abiertas",m.openIncidents||0],["Pendientes de confirmar",m.pendingApprovals||0],["Recursos activos",m.activeAssets||0]].map(([l,v])=><div key={l} className="card p-4"><div className="text-xs text-slate-500">{l}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>)}</div><a href="/dashboard/trace-management" className="btn-secondary inline-flex">Reportes e importaciones</a></section>}

  <TraceControlWizard solution={solution} name={controlName} setName={setControlName} users={options.users||[]} selectedUsers={selectedUsers} toggleUser={id=>toggle(selectedUsers,setSelectedUsers,id)} departments={options.departments||[]} selectedDepartments={selectedDepartments} toggleDepartment={id=>toggle(selectedDepartments,setSelectedDepartments,id)} publicView={publicView} setPublicView={setPublicView} busy={busy} onClose={()=>setSolution(null)} onCreate={create}/>
  <TraceActivityModal open={activityOpen} work={work} executionId={executionId} setExecutionId={setExecutionId} type={activityType} setType={setActivityType} description={activityText} setDescription={setActivityText} busy={busy} onClose={()=>setActivityOpen(false)} onSave={saveActivity}/>
 </div>;
}
