import { useEffect, useMemo, useState } from "react";
import TraceCommandShell from "../components/trace/TraceCommandShell.jsx";
import TraceControlWizard from "../components/trace/TraceControlWizard.jsx";
import TraceActivityModal from "../components/trace/TraceActivityModal.jsx";

const BASE = import.meta.env.VITE_API_URL || "https://api.code.intaprd.com";
const API = "/api/trace/v1/admin";
const CC = `${API}/command-center`;

function auth(extra={}) { const token=localStorage.getItem("qr_token")||""; return {...(token?{Authorization:`Bearer ${token}`}:{}) ,...extra}; }
async function req(path, options={}) { const r=await fetch(`${BASE}${path}`,{...options,headers:auth({"Content-Type":"application/json",...(options.headers||{})})}); const d=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`})); if(!r.ok||d?.ok===false) throw new Error(d?.message||d?.error||`HTTP ${r.status}`); return d; }
function labelStatus(v){return({pending:"Pendiente",assigned:"Asignado",available:"Disponible",in_progress:"En curso",pending_approval:"Por confirmar",correction_required:"Requiere corrección",completed:"Completado",approved:"Aprobado",overdue:"Atrasado",blocked:"Bloqueado",open:"Abierta"}[v]||String(v||"Pendiente").replaceAll("_"," "));}
function Tone({value}){const cls=["completed","approved"].includes(value)?"bg-emerald-50 text-emerald-700 border-emerald-200":["blocked","overdue"].includes(value)?"bg-red-50 text-red-700 border-red-200":["correction_required","pending_approval","open"].includes(value)?"bg-amber-50 text-amber-700 border-amber-200":"bg-blue-50 text-blue-700 border-blue-200";return <span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${cls}`}>{labelStatus(value)}</span>}
function initials(email="?"){return email.split("@")[0].split(/[._-]/).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?";}

export default function TraceCommandCenterPage(){
 const [view,setView]=useState("home");
 const [overview,setOverview]=useState({metrics:{},processes:[],executions:[],incidents:[],approvals:[]});
 const [templates,setTemplates]=useState([]),[options,setOptions]=useState({users:[],departments:[]});
 const [workspace,setWorkspace]=useState(null),[selectedExecution,setSelectedExecution]=useState("");
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [solution,setSolution]=useState(null),[controlName,setControlName]=useState(""),[selectedUsers,setSelectedUsers]=useState([]),[selectedDepartments,setSelectedDepartments]=useState([]),[publicView,setPublicView]=useState(true);
 const [activityOpen,setActivityOpen]=useState(false),[activityText,setActivityText]=useState(""),[activityType,setActivityType]=useState("progress.updated"),[busy,setBusy]=useState(false);

 async function load(){setLoading(true);setError("");try{const[o,t,s]=await Promise.all([req(`${API}/overview`),req(`${API}/templates`),req(`${API}/setup-options`)]);setOverview(o.data||{});setTemplates(t.data||[]);setOptions(s.data||{users:[],departments:[]});}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function openExecution(id){if(!id)return;setSelectedExecution(id);setError("");try{const d=await req(`${CC}/executions/${encodeURIComponent(id)}`);setWorkspace(d.data);setView("operations");}catch(e){setError(e.message)}}
 async function assign(stageId,userId){if(!userId)return;setBusy(true);try{await req(`${CC}/stages/${encodeURIComponent(stageId)}/assign`,{method:"POST",body:JSON.stringify({userId})});await openExecution(selectedExecution);setMessage("Responsable asignado.");}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function saveActivity(){if(!selectedExecution||!activityText.trim())return setError("Selecciona una operación y describe lo ocurrido.");setBusy(true);try{await req(`${API}/activities`,{method:"POST",body:JSON.stringify({executionId:selectedExecution,type:activityType,description:activityText.trim()})});setActivityOpen(false);setActivityText("");await load();await openExecution(selectedExecution);setMessage("Actividad registrada en la bitácora.");}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function createControl(){if(!solution||!controlName.trim())return;setBusy(true);try{const d=await req(`${API}/controls`,{method:"POST",body:JSON.stringify({templateId:solution.id,name:controlName.trim(),responsibleUserIds:selectedUsers,departmentIds:selectedDepartments,publicView})});setSolution(null);setMessage(`Control activado: ${d.data.name}.`);await load();setView("home");}catch(e){setError(e.message)}finally{setBusy(false)}}
 const m=overview.metrics||{},work=overview.executions||[],incidents=overview.incidents||[],approvals=overview.approvals||[];
 const construction=useMemo(()=>templates.filter(t=>["construction","property","rental","maintenance"].includes(t.industry)),[templates]);
 const other=useMemo(()=>templates.filter(t=>!["construction","property","rental","maintenance"].includes(t.industry)),[templates]);
 const current=workspace?.execution;
 const attention=(m.openIncidents||0)+(m.correctionStages||0)+(m.pendingApprovals||0);
 function toggle(list,setter,id){setter(list.includes(id)?list.filter(x=>x!==id):[...list,id])}

 return <TraceCommandShell view={view} onView={setView} onNewControl={()=>setView("solutions")} onRegister={()=>{setSelectedExecution(work[0]?.id||selectedExecution);setActivityOpen(true)}}>
  {error&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
  {message&&<div className="mb-4 flex items-center justify-between rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700"><span>{message}</span><button onClick={()=>setMessage("")} className="font-bold">×</button></div>}

  {view==="home"&&<div className="space-y-6">
   <section className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-semibold text-blue-600">Centro de mando</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950">¿Qué necesita tu atención hoy?</h1><p className="mt-2 text-sm text-slate-500">Una vista de la operación para decidir y actuar desde el mismo lugar.</p></div><select className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"><option>Todos los proyectos y controles</option>{work.map(w=><option key={w.id}>{w.title||w.process_name}</option>)}</select></section>
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    {[{t:"Trabajos en curso",v:m.inProgress||0,n:"Ver operación activa",go:"operations"},{t:"Necesitan atención",v:attention,n:`${m.openIncidents||0} incidencias abiertas`,go:"supervision"},{t:"Por confirmar",v:m.pendingApprovals||0,n:"Revisiones y aprobaciones",go:"supervision"},{t:"Controles activos",v:m.activeProcesses||0,n:"Soluciones funcionando",go:"solutions"}].map((x,i)=><button key={x.t} onClick={()=>setView(x.go)} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><div className="flex items-start justify-between"><span className="text-xs font-semibold text-slate-500">{x.t}</span><span className={`grid h-8 w-8 place-items-center rounded-xl ${i===1&&x.v?"bg-red-50 text-red-600":"bg-blue-50 text-blue-600"}`}>↗</span></div><div className="mt-3 text-3xl font-black text-slate-950">{x.v}</div><div className="mt-2 text-xs text-slate-500">{x.n}</div></button>)}
   </section>
   <section className="grid gap-5 xl:grid-cols-[1.65fr_.85fr]">
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold text-slate-950">Operaciones activas</h2><p className="text-xs text-slate-500">Selecciona una para abrir su centro de trabajo.</p></div><span className="text-xs font-semibold text-blue-600">{work.length} visibles</span></div><div className="divide-y divide-slate-100">{work.slice(0,8).map(w=><button key={w.id} onClick={()=>openExecution(w.id)} className="grid w-full gap-3 px-5 py-4 text-left transition hover:bg-blue-50/50 md:grid-cols-[1.4fr_.65fr_.5fr_auto] md:items-center"><div><div className="text-sm font-bold text-slate-900">{w.title||w.process_name}</div><div className="mt-1 text-xs text-slate-500">{w.asset_name||w.execution_code}</div></div><div><div className="mb-1 flex justify-between text-[11px] text-slate-500"><span>Avance</span><b>{Number(w.completion_percentage||0)}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Number(w.completion_percentage||0)}%`}}/></div></div><Tone value={w.status}/><span className="text-lg text-slate-400">›</span></button>)}{!work.length&&<div className="p-10 text-center text-sm text-slate-500">Todavía no hay operaciones en curso.</div>}</div></div>
    <div className="space-y-5"><div className="rounded-2xl bg-slate-950 p-5 text-white shadow-sm"><div className="text-xs font-semibold uppercase tracking-wider text-blue-300">Atención prioritaria</div><div className="mt-3 text-4xl font-black">{attention}</div><p className="mt-2 text-sm text-slate-300">Elementos requieren revisión, corrección o confirmación.</p><button onClick={()=>setView("supervision")} className="mt-5 w-full rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-950">Abrir supervisión</button></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-950">Actividad reciente</h3><div className="mt-4 space-y-4">{incidents.slice(0,3).map(i=><button key={i.id} onClick={()=>setView("supervision")} className="flex w-full gap-3 text-left"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-amber-400"/><div><div className="text-sm font-semibold text-slate-800">{i.title}</div><div className="text-xs text-slate-500">{i.execution_title||i.execution_code}</div></div></button>)}{!incidents.length&&<p className="text-sm text-slate-500">Sin novedades importantes.</p>}</div></div></div>
   </section>
  </div>}

  {view==="operations"&&<div className="space-y-5">{!current?<div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><h2 className="text-xl font-bold">Selecciona una operación</h2><p className="mt-2 text-sm text-slate-500">Abre una operación desde el Centro de mando.</p><button onClick={()=>setView("home")} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Volver al centro de mando</button></div>:<>
   <section className="rounded-3xl bg-gradient-to-br from-slate-950 to-slate-800 p-6 text-white shadow-lg"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-blue-300">{current.execution_code}</div><h1 className="mt-2 text-3xl font-black">{current.title||current.process_name}</h1><p className="mt-2 text-sm text-slate-300">{current.asset_name||current.process_name}</p></div><div className="min-w-[260px]"><div className="flex items-end justify-between"><span className="text-sm text-slate-300">Avance general</span><span className="text-3xl font-black">{Number(current.completion_percentage||0)}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-blue-500" style={{width:`${Number(current.completion_percentage||0)}%`}}/></div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>{labelStatus(current.status)}</span><span>Actualizado recientemente</span></div></div></div></section>
   <section className="grid gap-5 xl:grid-cols-[1fr_300px]"><div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-slate-950">Ruta del trabajo</h2><p className="text-xs text-slate-500">Arrastra una persona sobre una etapa para asignarla.</p></div><span className="text-xs font-semibold text-blue-600">Arrastrar y soltar habilitado</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{(workspace.stages||[]).map((s,index)=><div key={s.id} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("ring-2","ring-blue-400")}} onDragLeave={e=>e.currentTarget.classList.remove("ring-2","ring-blue-400")} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove("ring-2","ring-blue-400");assign(s.id,e.dataTransfer.getData("text/trace-user"))}} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition"><div className="flex items-start gap-3"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-black ${["completed","approved"].includes(s.status)?"bg-emerald-100 text-emerald-700":"bg-blue-100 text-blue-700"}`}>{index+1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-bold text-slate-900">{s.name}</h3><Tone value={s.status}/></div><p className="mt-1 text-xs leading-5 text-slate-500">{s.description||"Etapa operativa"}</p><div className="mt-3 flex items-center justify-between gap-2 rounded-xl border border-dashed border-slate-300 bg-white px-3 py-2"><div className="flex min-w-0 items-center gap-2">{s.assigned_email?<><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-600 text-[10px] font-bold text-white">{initials(s.assigned_email)}</span><span className="truncate text-xs font-semibold text-slate-700">{s.assigned_email}</span></>:<span className="text-xs text-slate-400">Suelta aquí un responsable</span>}</div><select disabled={busy} value={s.assigned_to||""} onChange={e=>assign(s.id,e.target.value)} className="max-w-[125px] rounded-lg border border-slate-200 bg-white px-2 py-1 text-[11px]"><option value="">Asignar…</option>{(workspace.users||[]).map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></div></div></div></div>)}</div></div>
   <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-950">Evidencias recientes</h2><span className="text-xs font-bold text-blue-600">{workspace.evidences?.length||0}</span></div><div className="mt-4 grid grid-cols-2 gap-3">{(workspace.evidences||[]).slice(0,4).map((e,i)=><div key={e.id} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="grid aspect-[4/3] place-items-center rounded-lg bg-gradient-to-br from-slate-100 to-slate-200 text-2xl">▧</div><div className="mt-2 truncate text-xs font-semibold text-slate-700">{e.caption||e.original_filename||`Evidencia ${i+1}`}</div></div>)}{!workspace.evidences?.length&&<div className="col-span-2 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Las fotos y archivos aparecerán aquí.</div>}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">Bitácora</h2><div className="mt-4 space-y-4">{(workspace.events||[]).slice(0,5).map(e=><div key={e.id} className="flex gap-3"><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-blue-500"/><div><div className="text-sm font-semibold text-slate-800">{e.description||labelStatus(e.event_type)}</div><div className="text-[11px] text-slate-400">{e.occurred_at}</div></div></div>)}{!workspace.events?.length&&<p className="text-sm text-slate-500">Sin actividad todavía.</p>}</div></div></div>
   </div><aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-bold text-slate-950">Personas disponibles</h3><p className="mt-1 text-xs text-slate-500">Arrastra sobre una etapa o usa el selector.</p><div className="mt-4 space-y-2">{(workspace.users||[]).map(u=><div key={u.id} draggable onDragStart={e=>{e.dataTransfer.setData("text/trace-user",u.id);e.dataTransfer.effectAllowed="copy"}} className="flex cursor-grab items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 transition hover:border-blue-300 hover:shadow-sm active:cursor-grabbing"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-900 text-xs font-black text-white">{initials(u.email)}</span><div className="min-w-0"><div className="truncate text-xs font-bold text-slate-800">{u.email.split("@")[0]}</div><div className="truncate text-[10px] text-slate-400">{u.email}</div></div><span className="ml-auto text-slate-300">⠿</span></div>)}</div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-bold uppercase tracking-wider text-amber-700">Atención</div><div className="mt-3 text-3xl font-black text-amber-950">{workspace.incidents?.filter(i=>!["resolved","validated","closed"].includes(i.status)).length||0}</div><div className="text-sm font-semibold text-amber-900">incidencias abiertas</div><button onClick={()=>setView("supervision")} className="mt-4 w-full rounded-xl bg-amber-900 px-3 py-2.5 text-sm font-bold text-white">Revisar incidencias</button></div></aside></section>
  </>}</div>}

  {view==="supervision"&&<div className="space-y-5"><div><p className="text-sm font-semibold text-blue-600">Supervisión</p><h1 className="mt-1 text-3xl font-black text-slate-950">Atención y decisiones</h1></div><div className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Incidencias y correcciones</h2></div><div className="divide-y">{incidents.map(i=><div key={i.id} className="flex items-center gap-4 p-4"><span className={`h-3 w-3 rounded-full ${i.severity==="critical"?"bg-red-500":i.severity==="high"?"bg-orange-500":"bg-amber-400"}`}/><div className="min-w-0 flex-1"><div className="text-sm font-bold text-slate-900">{i.title}</div><div className="text-xs text-slate-500">{i.execution_title||i.execution_code}</div></div><Tone value={i.status}/></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Pendientes de confirmar</h2></div><div className="divide-y">{approvals.map(a=><div key={a.id} className="flex items-center justify-between gap-4 p-4"><div><div className="text-sm font-bold text-slate-900">{a.execution_title||a.execution_code}</div><div className="text-xs text-slate-500">{a.stage_name||"Revisión"}</div></div><Tone value={a.status}/></div>)}</div></div></div>}

  {view==="solutions"&&<div className="space-y-7"><div><p className="text-sm font-semibold text-blue-600">Biblioteca de soluciones</p><h1 className="mt-1 text-3xl font-black text-slate-950">Empieza con el trabajo ya armado</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">TRACE carga etapas, evidencias, revisiones y reglas base. Tú asignas personas y ajustas lo particular.</p></div>{[["Construcción, propiedades y mantenimiento",construction],["Otros sectores",other]].map(([title,list])=><section key={title}><h2 className="mb-3 font-bold text-slate-900">{title}</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map(t=><button key={t.id} onClick={()=>{setSolution(t);setControlName(t.name);setSelectedUsers([]);setSelectedDepartments([]);setPublicView(true)}} className="group rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-md"><div className="flex items-center justify-between"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold uppercase text-blue-700">{t.industry}</span><span className="text-xl text-blue-500">↗</span></div><h3 className="mt-4 text-lg font-black text-slate-950">{t.name}</h3><p className="mt-2 text-sm leading-5 text-slate-500">{t.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-xs"><span className="font-bold text-slate-700">{t.stages?.length||0} pasos preparados</span><span className="text-blue-600">Ver solución</span></div></button>)}</div></section>)}</div>}

  {view==="evaluations"&&<div className="space-y-5"><div><p className="text-sm font-semibold text-blue-600">Evaluaciones</p><h1 className="mt-1 text-3xl font-black text-slate-950">Control de calidad y experiencia</h1><p className="mt-2 text-sm text-slate-500">Listas de revisión, calificaciones y encuestas conectadas al trabajo real.</p></div><div className="grid gap-4 md:grid-cols-3">{[["✓","Listas de revisión","Verifica puntos, evidencia hallazgos y genera acciones."],["★","Calificaciones","Mide calidad de trabajos, entregas o servicios."],["◌","Encuestas","Recoge satisfacción y nivel de recomendación."]].map(x=><button key={x[1]} onClick={()=>setView("solutions")} className="rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm hover:border-blue-300"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-lg font-black text-blue-600">{x[0]}</span><h3 className="mt-4 text-lg font-black">{x[1]}</h3><p className="mt-2 text-sm text-slate-500">{x[2]}</p></button>)}</div></div>}

  {view==="reports"&&<div className="space-y-5"><div><p className="text-sm font-semibold text-blue-600">Reportes</p><h1 className="mt-1 text-3xl font-black text-slate-950">Resultados que se pueden leer de un vistazo</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Avance promedio",work.length?Math.round(work.reduce((a,w)=>a+Number(w.completion_percentage||0),0)/work.length):0,"%"],["Incidencias abiertas",m.openIncidents||0,""],["Trabajos completados",m.completed||0,""],["Recursos activos",m.activeAssets||0,""]].map(([l,v,s])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-semibold text-slate-500">{l}</div><div className="mt-2 text-3xl font-black">{v}{s}</div></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Avance por operación</h2><div className="mt-5 space-y-4">{work.slice(0,6).map(w=><div key={w.id}><div className="mb-1 flex justify-between text-xs"><span className="font-semibold text-slate-700">{w.title||w.process_name}</span><b>{Number(w.completion_percentage||0)}%</b></div><div className="h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Number(w.completion_percentage||0)}%`}}/></div></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Estado de atención</h2><div className="mt-5 flex items-center gap-6"><div className="grid h-36 w-36 place-items-center rounded-full" style={{background:`conic-gradient(#2563eb 0 ${Math.min(100,Math.max(1,100-attention*10))}%,#e2e8f0 0)`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white"><div className="text-center"><div className="text-2xl font-black">{attention}</div><div className="text-[10px] text-slate-500">por atender</div></div></div></div><div className="space-y-2 text-sm"><div><b>{m.openIncidents||0}</b> incidencias</div><div><b>{m.pendingApprovals||0}</b> por confirmar</div><div><b>{m.correctionStages||0}</b> correcciones</div></div></div></div></div></div>}

  {solution&&<TraceControlWizard solution={solution} name={controlName} setName={setControlName} options={options} selectedUsers={selectedUsers} selectedDepartments={selectedDepartments} onToggleUser={id=>toggle(selectedUsers,setSelectedUsers,id)} onToggleDepartment={id=>toggle(selectedDepartments,setSelectedDepartments,id)} publicView={publicView} setPublicView={setPublicView} busy={busy} onClose={()=>setSolution(null)} onCreate={createControl}/>} 
  {activityOpen&&<TraceActivityModal work={work} executionId={selectedExecution} setExecutionId={setSelectedExecution} activityType={activityType} setActivityType={setActivityType} text={activityText} setText={setActivityText} busy={busy} onClose={()=>setActivityOpen(false)} onSave={saveActivity}/>} 
 </TraceCommandShell>
}
