import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import QRCode from "qrcode";
import { useAuth } from "../context/AuthContext.jsx";

export default function TraceActivationConfirmPage(){
 const nav=useNavigate(); const{user}=useAuth(); const canvasRef=useRef(null); const[copied,setCopied]=useState(false);
 const draft=useMemo(()=>{try{return JSON.parse(localStorage.getItem("trace_onboarding_draft")||"{}")}catch{return{}}},[]);
 const result=useMemo(()=>{try{return JSON.parse(localStorage.getItem("trace_activation_result")||"{}")}catch{return{}}},[]);
 const publicUrl=result.publicPath?`${window.location.origin}${result.publicPath}`:"";
 useEffect(()=>{if(user?.id)localStorage.setItem(`trace_onboarding_done_${user.id}`,"1");localStorage.setItem("trace_onboarding_done","1");if(publicUrl&&canvasRef.current)QRCode.toCanvas(canvasRef.current,publicUrl,{width:220,margin:1,errorCorrectionLevel:"M"}).catch(()=>{})},[user?.id,publicUrl]);
 async function copy(){if(!publicUrl)return;await navigator.clipboard.writeText(publicUrl);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 function download(){const c=canvasRef.current;if(!c)return;const a=document.createElement("a");a.download=`trace-${result.slug||"proyecto"}.png`;a.href=c.toDataURL("image/png");a.click()}
 return <div className="min-h-screen bg-white text-slate-950"><div className="mx-auto max-w-[1120px] px-5 py-8 sm:px-8"><header className="flex items-center justify-between"><div className="flex items-baseline gap-2"><b className="text-2xl">KAWVO</b><span className="text-2xl font-semibold text-blue-600">Trace</span></div><div className="flex items-center gap-5 text-sm"><span>Configuración completada</span><div className="flex gap-3">{[1,2,3,4].map(n=><span key={n} className="h-4 w-4 rounded-full bg-blue-600"/>)}</div></div></header><main className="mx-auto mt-14 max-w-[900px]"><div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-green-50 text-3xl font-black text-green-600">✓</span><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Trace está activo</h1><p className="mt-3 text-base text-slate-600">Tu espacio ya tiene proyecto, equipo, responsabilidades y seguimiento configurado.</p></div><section className="mt-9 grid gap-6 rounded-2xl border border-slate-200 p-5 sm:p-7 md:grid-cols-[1fr_280px]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Proyecto</p><h2 className="mt-2 text-2xl font-black">{draft.operationName||"Proyecto TRACE"}</h2><p className="mt-2 text-sm text-slate-500">{draft.rubroLabel}{draft.operation?` · ${draft.operation}`:""}</p><div className="mt-7"><p className="text-sm font-black">Enlace público del proyecto</p><div className="mt-2 flex flex-col gap-2 sm:flex-row"><div className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600 break-all">{publicUrl||"Enlace no disponible"}</div><button onClick={copy} disabled={!publicUrl} className="rounded-xl border border-blue-500 px-5 py-3 text-sm font-black text-blue-600">{copied?"Copiado":"Copiar"}</button></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>nav("/trace")} className="rounded-xl bg-blue-600 px-6 py-4 text-sm font-black text-white">Ir al panel de Trace</button><button onClick={()=>publicUrl&&window.open(publicUrl,"_blank","noopener,noreferrer")} disabled={!publicUrl} className="rounded-xl border border-slate-300 px-6 py-4 text-sm font-black text-slate-700">Ver enlace público</button></div></div><div className="grid place-items-center rounded-2xl bg-slate-50 p-5"><canvas ref={canvasRef} className="max-w-full rounded-xl bg-white"/><button onClick={download} disabled={!publicUrl} className="mt-4 text-sm font-black text-blue-600">Descargar QR</button></div></section><p className="mt-5 text-center text-xs text-slate-400">Las invitaciones por correo se gestionan con el sistema actual de equipo. WhatsApp se habilitará cuando exista un canal real conectado.</p></main></div></div>
}
