import {useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";

const BASE=import.meta.env.VITE_API_URL||"https://api.code.intaprd.com";
const ROLES={
 manager:{label:"Administrar",tone:"blue",desc:"Configura el proyecto y gestiona al equipo",permissions:["Configurar el proyecto","Gestionar al equipo y roles","Aprobar avances e incidencias","Ver todos los reportes y evidencias","Descargar documentos y evidencias"]},
 supervisor:{label:"Supervisar",tone:"green",desc:"Revisa avances, incidencias y aprobaciones",permissions:["Revisar avances","Aprobar o devolver registros","Asignar correcciones","Gestionar incidencias","Consultar reportes y evidencias"]},
 member:{label:"Registrar avances",tone:"orange",desc:"Registra actividades, fotos e incidencias",permissions:["Registrar actividades","Subir fotografías y documentos","Reportar incidencias","Actualizar tareas asignadas","Consultar sus propios registros"]},
 observer:{label:"Consultar el proyecto",tone:"violet",desc:"Consulta avances y evidencias autorizadas",permissions:["Ver avance autorizado","Consultar hitos y evidencias","Ver incidencias compartidas","Recibir actualizaciones"]}
};
const TONES={blue:"border-blue-500 bg-blue-50 text-blue-700",green:"border-green-500 bg-green-50 text-green-700",orange:"border-orange-500 bg-orange-50 text-orange-700",violet:"border-violet-400 bg-violet-50 text-violet-700"};
function headers(){const t=localStorage.getItem("qr_token")||"";return{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}}
function initials(v=""){return v.split(/[@.\s_-]+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"U"}
function Progress(){return <div className="flex items-center gap-5 text-sm"><span>Paso 3 de 4</span><div className="flex gap-6">{[1,2,3,4].map(n=><span key={n} className={`h-4 w-4 rounded-full ${n<=3?"bg-blue-600":"bg-slate-200"}`}/>)}</div></div>}
function Brand(){return <div className="flex items-baseline gap-2"><b className="text-2xl">KAWVO</b><span className="text-2xl font-semibold text-blue-600">Trace</span></div>}
export default function TraceTeamSetupPage(){
 const nav=useNavigate();const[draft]=useState(()=>{try{return JSON.parse(localStorage.getItem("trace_onboarding_draft")||"{}")}catch{return{}}});
 const[people,setPeople]=useState([]),[assignments,setAssignments]=useState({}),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[inviteOpen,setInviteOpen]=useState(false),[email,setEmail]=useState(""),[saving,setSaving]=useState(false);
 const projectId=draft.projectId||"";
 async function load(){setLoading(true);setError("");try{const r=await fetch(`${BASE}/api/trace/v1/admin/workspace`,{headers:headers()});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||"No fue posible cargar el equipo");setPeople(d.data?.people||[]);const pd=projectId?await fetch(`${BASE}/api/trace/v1/admin/workspace/projects/${encodeURIComponent(projectId)}`,{headers:headers()}):null;if(pd){const x=await pd.json();if(pd.ok){const a={};(x.data?.people||[]).forEach(p=>a[p.user_id]=p.project_role);setAssignments(a);setSelected(Object.keys(a)[0]||"")}}}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(!projectId){nav("/trace/setup/company",{replace:true});return}load()},[projectId]);
 const selectedPerson=useMemo(()=>people.find(p=>p.id===selected),[people,selected]);const selectedRole=ROLES[assignments[selected]];
 function assign(userId,role){setAssignments(a=>({...a,[userId]:role}));setSelected(userId)}
 async function invite(e){e.preventDefault();if(!email.trim())return;setSaving(true);setError("");try{const r=await fetch(`${BASE}/api/team/invite`,{method:"POST",headers:headers(),body:JSON.stringify({email:email.trim(),role:"viewer"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||"No fue posible enviar la invitación");setEmail("");setInviteOpen(false);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function save(next=true){setSaving(true);setError("");try{for(const[userId,projectRole]of Object.entries(assignments)){const r=await fetch(`${BASE}/api/trace/v1/admin/workspace/projects/${encodeURIComponent(projectId)}/participants`,{method:"POST",headers:headers(),body:JSON.stringify({userId,projectRole})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||"No fue posible guardar una responsabilidad")};localStorage.setItem("trace_onboarding_draft",JSON.stringify({...draft,teamAssignments:assignments,step:3}));if(next)nav("/trace/setup/review")}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="min-h-screen bg-white text-slate-950"><div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8"><header className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><Brand/><Progress/></header><main className="mt-8"><h1 className="text-4xl font-black tracking-[-.035em] sm:text-5xl">Agrega a tu equipo</h1><p className="mt-2 text-base text-slate-600">Invita a las personas que participarán y asigna lo que podrán hacer.</p><div className="mt-4 inline-flex rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">▦&nbsp;&nbsp;{draft.operationName||"Proyecto"}&nbsp;&nbsp;·&nbsp;&nbsp;{draft.operation||draft.rubroLabel||"Operación"}</div>{error&&<div className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <div className="mt-6 grid gap-8 xl:grid-cols-2"><section><h2 className="mb-3 text-xl font-black">Personas</h2>{loading?<div className="rounded-2xl border border-slate-200 p-8 text-sm text-slate-400">Cargando equipo…</div>:<div className="space-y-2">{people.map(p=>{const role=assignments[p.id];return <button key={p.id} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",p.id)} onClick={()=>setSelected(p.id)} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left ${selected===p.id?"border-blue-500 ring-2 ring-blue-100":"border-slate-200"}`}><span className="text-xl text-slate-400">⠿</span><span className="grid h-11 w-11 place-items-center rounded-full bg-blue-100 font-black text-blue-800">{initials(p.email)}</span><span className="min-w-0 flex-1"><b className="block truncate">{p.email}</b><span className="text-xs text-slate-400">Activo</span>{role&&<span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black text-slate-600">{ROLES[role]?.label}</span>}</span><span className="text-xl text-slate-400">›</span></button>})}<button onClick={()=>setInviteOpen(true)} className="w-full rounded-xl border border-blue-500 px-4 py-3 text-sm font-black text-blue-600">＋ Agregar persona</button></div>}</section>
 <section><h2 className="mb-3 text-xl font-black">Responsabilidades</h2><div className="space-y-3">{Object.entries(ROLES).map(([key,r])=><button key={key} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("text/plain");if(id)assign(id,key)}} onClick={()=>selected&&assign(selected,key)} className={`w-full rounded-xl border-2 p-4 text-left transition ${selected&&assignments[selected]===key?TONES[r.tone]:"border-slate-200 bg-white hover:border-slate-300"}`}><div className="flex items-start gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-50 text-xl">{key==="manager"?"♙":key==="supervisor"?"✓":key==="member"?"◉":"◉"}</span><span><b className="text-lg">{r.label}</b><span className="mt-1 block text-sm text-slate-500">{r.desc}</span></span></div></button>)}</div></section></div>
 {selectedPerson&&selectedRole&&<section className="mt-6 grid gap-5 rounded-2xl border border-slate-200 p-5 md:grid-cols-[300px_1fr]"><div className="flex items-center gap-4 md:border-r md:border-slate-200 md:pr-5"><span className="grid h-20 w-20 place-items-center rounded-full bg-blue-100 text-2xl font-black text-blue-800">{initials(selectedPerson.email)}</span><div><h3 className="text-xl font-black">{selectedPerson.email}</h3><span className="mt-2 inline-block rounded-lg border border-blue-500 px-3 py-1 text-sm font-black text-blue-600">{selectedRole.label}</span></div></div><div><h3 className="font-black">Qué puede hacer</h3><div className="mt-2 grid gap-2">{selectedRole.permissions.map(x=><div key={x} className="flex items-center gap-2 text-sm"><span className="grid h-5 w-5 place-items-center rounded-full bg-blue-600 text-[10px] text-white">✓</span>{x}</div>)}</div></div></section>}
 <div className="mt-7 flex flex-col gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:items-center sm:justify-between"><button onClick={()=>nav("/trace/setup/company")} className="rounded-xl border border-blue-500 px-8 py-3 text-sm font-black text-blue-600">Volver</button><button onClick={()=>save(true)} disabled={saving} className="text-sm font-black text-blue-600 disabled:text-slate-300">Configurar después</button><button onClick={()=>save(true)} disabled={saving} className="rounded-xl bg-blue-600 px-10 py-3 text-sm font-black text-white disabled:bg-slate-300">{saving?"Guardando…":"Guardar y continuar"}</button></div></main></div>
 {inviteOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={invite} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Agregar persona</h2><button type="button" onClick={()=>setInviteOpen(false)} className="text-2xl text-slate-400">×</button></div><label className="mt-5 grid gap-2 text-sm font-black">Correo electrónico<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="persona@empresa.com"/></label><div className="mt-4"><div className="text-sm font-black">Método de invitación</div><div className="mt-2 grid grid-cols-2 gap-2"><div className="rounded-xl border-2 border-blue-500 bg-blue-50 p-3 text-center text-sm font-black text-blue-700">Correo</div><div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-center text-sm font-black text-slate-400">WhatsApp · próximamente</div></div></div><button disabled={saving} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 font-black text-white">{saving?"Enviando…":"Agregar al equipo"}</button></form></div>}
 </div>}
